import { describe, it, expect } from "vitest";
import { provenanceLabel, type ProvenanceKind } from "@/app/_components/Provenance";

/**
 * Every figure in the catalogue was one of two things and looked like the
 * same thing: hand-written at the start of the project, or generated by
 * profile-gen. Sixty-eight contacts carried an audience or a rate; none
 * recorded a source. These pin the three standings apart so they cannot drift
 * back together across five screens.
 */
describe("a figure carries its own standing", () => {
  it("says an unsourced number is unsourced, out loud", () => {
    // Not "estimate" alone: an estimate sounds like someone estimated it.
    expect(provenanceLabel("estimate")).toBe("estimate — not sourced");
  });

  it("keeps confirmed distinct from sourced", () => {
    // A citation and a person agreeing on a call are different claims. The
    // second is the only one that is evidence.
    expect(provenanceLabel("confirmed")).not.toBe(provenanceLabel("sourced"));
    expect(provenanceLabel("confirmed")).toContain("on the call");
    expect(provenanceLabel("sourced")).not.toContain("call");
  });

  it("never lets a confirmed figure read as merely sourced", () => {
    const kinds: ProvenanceKind[] = ["estimate", "sourced", "confirmed"];
    expect(new Set(kinds.map(provenanceLabel)).size).toBe(3);
  });

  it("never calls an estimate sourced", () => {
    expect(provenanceLabel("estimate")).toContain("not sourced");
    expect(provenanceLabel("estimate")).not.toBe("sourced");
  });
});
