"""US federal jurisdiction rules (TCPA / FCC / FTC baseline).

Sourced from the multi-jurisdiction legal research report (2026-08-27),
Section 1. State-level variation (all-party consent states, state
mini-TCPA laws, state AI-disclosure laws) is out of scope here and must
be added as a separate state-level jurisdiction layer later.
"""

from __future__ import annotations

from datetime import datetime, timedelta
from datetime import timezone as dt_timezone

from ..models import (
    CallingWindow,
    CheckResult,
    ConfidenceLevel,
    JurisdictionRules,
    PreCallContext,
    RecordingConsentType,
)
from ..time_utils import UnknownTimezoneError, recipient_local_datetime

WINDOW_START_HOUR = 8
WINDOW_END_HOUR = 21  # exclusive; 47 CFR 64.1200(c)(1), local recipient time

# GRAY AREA (medium confidence, unverified against a primary source): a
# very recent, explicit consent is treated here as excusing an
# outside-window call. This is not a documented safe harbor in the
# research report - it is an interim product decision pending real legal
# review, kept short-lived (15 minutes) specifically so it cannot become a
# general-purpose way to bypass the calling window.
RECENT_CONSENT_WINDOW_EXCEPTION = timedelta(minutes=15)

DISCLOSURE_SCRIPT = (
    "Hello, I'm [AGENT_NAME], the AI voice assistant for [ENTITY], and I'm calling "
    "[REASON_FOR_CALLING] "
    "This call uses an artificial voice generated by artificial intelligence, "
    "as required by FCC rule 24-17. "
    "If you would like to reach us again, you can call [CALLBACK_NUMBER]."
)

RULES = JurisdictionRules(
    jurisdiction_id="us_federal",
    display_name="United States (federal baseline)",
    default_locale="en-US",
    region_code="US",
    calling_window=CallingWindow(start_local_hour=WINDOW_START_HOUR, end_local_hour=WINDOW_END_HOUR),
    consent_required=True,
    disclosure_required=True,
    disclosure_script=DISCLOSURE_SCRIPT,
    dnc_check_required=True,
    recording_consent_type=RecordingConsentType.ONE_PARTY,
    source_confidence=ConfidenceLevel.HIGH,
    notes=(
        "Federal baseline only; state-level variation is a separate future layer. "
        "GRAY AREA (medium confidence): the 15-minute recent-consent exception to "
        "the calling window is a product decision, not a confirmed legal safe "
        "harbor - see check_calling_window and RECENT_CONSENT_WINDOW_EXCEPTION."
    ),
)


def _now(context: PreCallContext) -> datetime:
    return context.now_utc or datetime.now(dt_timezone.utc)


def check_calling_window(context: PreCallContext) -> CheckResult:
    now_utc = _now(context)
    try:
        local_dt = recipient_local_datetime(now_utc, context.recipient_timezone)
    except UnknownTimezoneError as exc:
        return CheckResult("us_federal_calling_window", False, str(exc))

    in_window = WINDOW_START_HOUR <= local_dt.hour < WINDOW_END_HOUR
    if in_window:
        return CheckResult(
            "us_federal_calling_window",
            True,
            f"recipient local time {local_dt.strftime('%H:%M')} is within "
            f"{WINDOW_START_HOUR}:00-{WINDOW_END_HOUR}:00",
        )

    if context.consent_obtained and context.consent_timestamp is not None:
        age = now_utc - context.consent_timestamp
        if timedelta(0) <= age <= RECENT_CONSENT_WINDOW_EXCEPTION:
            return CheckResult(
                "us_federal_calling_window",
                True,
                f"recipient local time {local_dt.strftime('%H:%M')} is outside the window, but consent "
                f"was obtained {age} ago (<= 15 min); treated as an exception pending legal "
                "confirmation, not a documented FCC safe harbor",
                confidence=ConfidenceLevel.MEDIUM,
            )

    return CheckResult(
        "us_federal_calling_window",
        False,
        f"recipient local time {local_dt.strftime('%H:%M')} is outside "
        f"{WINDOW_START_HOUR}:00-{WINDOW_END_HOUR}:00 (47 CFR 64.1200(c)(1))",
    )


def check_consent(context: PreCallContext) -> CheckResult:
    if not context.consent_obtained or context.consent_timestamp is None:
        return CheckResult(
            "us_federal_consent",
            False,
            "prior express written consent (PEWC) not documented "
            "(consent_obtained/consent_timestamp missing)",
        )
    return CheckResult(
        "us_federal_consent", True, f"PEWC documented at {context.consent_timestamp.isoformat()}"
    )


def check_dnc_scrub(context: PreCallContext) -> CheckResult:
    if not context.dnc_checked:
        return CheckResult(
            "us_federal_dnc_scrub", False, "National DNC Registry scrub not confirmed (dnc_checked=False)"
        )
    return CheckResult("us_federal_dnc_scrub", True, "National DNC Registry scrub confirmed")


def check_disclosure_script() -> CheckResult:
    required_markers = ("[AGENT_NAME]", "[ENTITY]", "[CALLBACK_NUMBER]", "artificial")
    missing = [marker for marker in required_markers if marker not in DISCLOSURE_SCRIPT]
    if missing:
        return CheckResult(
            "us_federal_disclosure_script", False, f"disclosure_script is missing required elements: {missing}"
        )
    return CheckResult(
        "us_federal_disclosure_script",
        True,
        "disclosure_script includes caller identification, entity, callback number, "
        "and artificial-voice disclosure (FCC 24-17)",
    )


def check_revocation(context: PreCallContext) -> CheckResult:
    if context.do_not_call_requested:
        return CheckResult(
            "us_federal_revocation", False, "do_not_call_requested is set; consent has been revoked (FCC 24-24)"
        )
    return CheckResult("us_federal_revocation", True, "no revocation on record")


def check(context: PreCallContext) -> list[CheckResult]:
    return [
        check_calling_window(context),
        check_consent(context),
        check_dnc_scrub(context),
        check_disclosure_script(),
        check_revocation(context),
    ]
