import type { CenterCallRecord, CenterCandidate, CenterResult, SearchBrief, TranscriptTurn } from "./types.ts";

export const fixtureBrief: SearchBrief = {
  ageBand: "toddler",
  desiredStartDate: "2026-10-15",
  requiredWeekdays: ["monday", "wednesday", "friday"],
  dropoffTime: "08:30",
  pickupTime: "17:30",
  budgetMonthlyMinor: 150000,
  currency: "USD",
  subsidyRequired: false,
  targetMatches: 2,
};

export const fixtureCandidates: CenterCandidate[] = [
  { id: "willow-room", name: "Willow Room Childcare", neighborhood: "North Park", distanceMiles: 1.8, source: "Operator-provided directory", demoPhone: "+12025550121", priority: 1 },
  { id: "alder-house", name: "Alder House Early Learning", neighborhood: "Riverside", distanceMiles: 2.4, source: "Operator-provided directory", demoPhone: "+12025550122", priority: 2 },
  { id: "moss-and-moon", name: "Moss & Moon Nursery", neighborhood: "Old Town", distanceMiles: 3.1, source: "Operator-provided directory", demoPhone: "+12025550123", priority: 3 },
  { id: "little-atlas", name: "Little Atlas Academy", neighborhood: "East Market", distanceMiles: 3.7, source: "Operator-provided directory", demoPhone: "+12025550124", priority: 4 },
  { id: "juniper-yard", name: "Juniper Yard Preschool", neighborhood: "Cedar Hill", distanceMiles: 4.2, source: "Operator-provided directory", demoPhone: "+12025550125", priority: 5 },
  { id: "hearthside", name: "Hearthside Children's Center", neighborhood: "West End", distanceMiles: 4.9, source: "Operator-provided directory", demoPhone: "+12025550126", priority: 6 },
];

export const fixtureResults: Record<string, CenterResult> = {
  "willow-room": {
    lineOutcome: "reached_staff",
    businessConfirmed: "yes",
    ageBandAccepted: "yes",
    vacancyStatus: "available",
    earliestStartDate: "2026-10-05",
    availableWeekdays: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    openingTime: "08:00",
    closingTime: "18:00",
    monthlyTuitionMinor: 142000,
    registrationFeeMinor: 7500,
    subsidyStatus: "accepted",
    tourStatus: "offered",
    tourWindows: ["Thursday at 10:00", "Friday at 15:30"],
    availabilityEvidence: "We have one toddler opening from October fifth.",
    scheduleEvidence: "That place is available Monday through Friday, eight to six.",
    feeEvidence: "Tuition is fourteen hundred and twenty dollars monthly, plus a seventy-five dollar registration fee.",
  },
  "alder-house": {
    lineOutcome: "reached_staff",
    businessConfirmed: "yes",
    ageBandAccepted: "yes",
    vacancyStatus: "available",
    earliestStartDate: "2026-10-12",
    availableWeekdays: ["monday", "wednesday", "friday"],
    openingTime: "07:30",
    closingTime: "17:45",
    monthlyTuitionMinor: 138000,
    registrationFeeMinor: 10000,
    subsidyStatus: "unknown",
    tourStatus: "offered",
    tourWindows: ["Wednesday at 09:30", "Thursday at 16:00"],
    availabilityEvidence: "A Monday, Wednesday, Friday toddler place opens October twelfth.",
    scheduleEvidence: "We open at seven thirty and close at five forty-five.",
    feeEvidence: "It is thirteen eighty per month and one hundred to register.",
  },
  "moss-and-moon": {
    lineOutcome: "reached_staff",
    businessConfirmed: "yes",
    ageBandAccepted: "yes",
    vacancyStatus: "waitlist",
    earliestStartDate: "",
    availableWeekdays: [],
    openingTime: "08:00",
    closingTime: "17:00",
    monthlyTuitionMinor: 129000,
    registrationFeeMinor: 5000,
    subsidyStatus: "accepted",
    tourStatus: "not_offered",
    tourWindows: [],
    availabilityEvidence: "There is no current toddler opening; the waitlist is about four months.",
    scheduleEvidence: "Our normal hours are eight until five.",
    feeEvidence: "The current toddler rate is twelve ninety per month.",
  },
  "little-atlas": {
    lineOutcome: "reached_staff",
    businessConfirmed: "yes",
    ageBandAccepted: "yes",
    vacancyStatus: "available",
    earliestStartDate: "2026-10-01",
    availableWeekdays: ["tuesday", "thursday"],
    openingTime: "08:00",
    closingTime: "18:00",
    monthlyTuitionMinor: 118000,
    registrationFeeMinor: 8500,
    subsidyStatus: "accepted",
    tourStatus: "offered",
    tourWindows: ["Tuesday at 11:00"],
    availabilityEvidence: "We have a toddler opening from October first for Tuesdays and Thursdays.",
    scheduleEvidence: "The open place is two days only, Tuesday and Thursday.",
    feeEvidence: "Monthly tuition is eleven hundred and eighty dollars.",
  },
  "juniper-yard": {
    lineOutcome: "reached_staff",
    businessConfirmed: "yes",
    ageBandAccepted: "yes",
    vacancyStatus: "full",
    earliestStartDate: "",
    availableWeekdays: [],
    openingTime: "07:30",
    closingTime: "18:00",
    monthlyTuitionMinor: -1,
    registrationFeeMinor: -1,
    subsidyStatus: "unknown",
    tourStatus: "not_offered",
    tourWindows: [],
    availabilityEvidence: "Our toddler room is full for the rest of this year.",
    scheduleEvidence: "",
    feeEvidence: "",
  },
  "hearthside": {
    lineOutcome: "reached_staff",
    businessConfirmed: "yes",
    ageBandAccepted: "yes",
    vacancyStatus: "available",
    earliestStartDate: "2026-10-13",
    availableWeekdays: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    openingTime: "08:00",
    closingTime: "18:30",
    monthlyTuitionMinor: 146000,
    registrationFeeMinor: 5000,
    subsidyStatus: "accepted",
    tourStatus: "offered",
    tourWindows: ["Monday at 14:00", "Wednesday at 10:30"],
    availabilityEvidence: "One toddler opening is available from October thirteenth.",
    scheduleEvidence: "It can cover all five weekdays from eight until six thirty.",
    feeEvidence: "The monthly fee is fourteen sixty, plus fifty dollars to register.",
  },
};

export const fixtureSummaries: Record<string, string> = {
  "willow-room": "Staff confirmed one toddler opening before the requested start date, full weekday coverage, compatible hours, current tuition, subsidy acceptance, and two possible tour windows.",
  "alder-house": "Staff confirmed a Monday, Wednesday, and Friday toddler opening with compatible hours and tuition below the stated monthly budget. Subsidy acceptance was not established.",
  "moss-and-moon": "Staff confirmed the center serves toddlers but reported no current opening. The only option described was an estimated four-month waitlist.",
  "little-atlas": "Staff reported an opening, but only on Tuesday and Thursday, which does not cover the requested weekdays.",
  "juniper-yard": "Staff reported that the toddler room is full for the remainder of the year.",
  "hearthside": "Staff confirmed an opening that fits the requested date, weekdays, hours, and monthly budget.",
};

export const fixtureTranscripts: Record<string, TranscriptTurn[]> = {
  "willow-room": [
    { offsetSeconds: 0, speaker: "agent", text: "Hello, I am TinySlot, an AI assistant making a childcare availability enquiry for a parent. Are you willing to continue?" },
    { offsetSeconds: 7, speaker: "recipient", text: "Yes, this is Willow Room Childcare. I can help." },
    { offsetSeconds: 12, speaker: "agent", text: "Do you have a toddler opening by October fifteenth for Monday, Wednesday, and Friday from eight thirty to five thirty?" },
    { offsetSeconds: 22, speaker: "recipient", text: "We have one toddler opening from October fifth, and it is available Monday through Friday from eight to six." },
    { offsetSeconds: 33, speaker: "agent", text: "What are the current monthly tuition, registration fee, subsidy status, and possible tour times?" },
    { offsetSeconds: 41, speaker: "recipient", text: "Tuition is fourteen hundred and twenty dollars monthly, registration is seventy-five, we accept subsidies, and tours are Thursday at ten or Friday at three thirty." },
  ],
  "alder-house": [
    { offsetSeconds: 0, speaker: "agent", text: "Hello, I am TinySlot, an AI assistant calling about current toddler availability. May I continue?" },
    { offsetSeconds: 6, speaker: "recipient", text: "Yes, you have reached Alder House Early Learning." },
    { offsetSeconds: 11, speaker: "agent", text: "Is there an opening by October fifteenth for Monday, Wednesday, and Friday care from eight thirty to five thirty?" },
    { offsetSeconds: 20, speaker: "recipient", text: "A three-day toddler place opens October twelfth. We are open from seven thirty until five forty-five." },
    { offsetSeconds: 29, speaker: "agent", text: "What is the current tuition and can a parent arrange a tour?" },
    { offsetSeconds: 35, speaker: "recipient", text: "It is thirteen eighty per month and one hundred to register. Tours are Wednesday morning or Thursday at four." },
  ],
  "moss-and-moon": [
    { offsetSeconds: 0, speaker: "agent", text: "Hello, I am TinySlot, an AI assistant making a childcare availability enquiry. Are you willing to continue?" },
    { offsetSeconds: 7, speaker: "recipient", text: "Yes, this is Moss and Moon Nursery." },
    { offsetSeconds: 11, speaker: "agent", text: "Do you have a current toddler opening for Monday, Wednesday, and Friday?" },
    { offsetSeconds: 18, speaker: "recipient", text: "No, there is no current toddler opening. The waitlist is about four months." },
    { offsetSeconds: 25, speaker: "agent", text: "What are your normal hours and current monthly rate?" },
    { offsetSeconds: 30, speaker: "recipient", text: "Our normal hours are eight until five, and the toddler rate is twelve ninety per month." },
  ],
};

export const initialRecords: CenterCallRecord[] = fixtureCandidates.map((candidate, index) => ({
  candidateId: candidate.id,
  status: index < 3 ? "planned" : "held",
  result: null,
  source: "fixture",
}));

export const fixtureTourResult = {
  outcome: "confirmed",
  confirmedWindow: "Thursday at 10:00",
  nextStep: "Ask for Maya at reception and bring photo identification.",
  reference: "Tour with Maya",
  evidence: "I have you down for Thursday at ten. Please ask for Maya.",
};
