import type { CenterCallRecord, CenterCandidate, CenterResult, SearchBrief } from "./types.ts";

export const fixtureBrief: SearchBrief = {
  ageBand: "toddler",
  desiredStartDate: "2026-10-15",
  requiredWeekdays: ["monday", "wednesday", "friday"],
  dropoffTime: "08:30",
  pickupTime: "17:30",
  budgetMonthlyMinor: 150000,
  currency: "USD",
  subsidyRequired: false,
  targetMatches: 2,
};

export const fixtureCandidates: CenterCandidate[] = [
  { id: "willow-room", name: "Willow Room Childcare", neighborhood: "North Park", distanceMiles: 1.8, source: "Operator-provided directory", demoPhone: "+12025550121", priority: 1 },
  { id: "alder-house", name: "Alder House Early Learning", neighborhood: "Riverside", distanceMiles: 2.4, source: "Operator-provided directory", demoPhone: "+12025550122", priority: 2 },
  { id: "moss-and-moon", name: "Moss & Moon Nursery", neighborhood: "Old Town", distanceMiles: 3.1, source: "Operator-provided directory", demoPhone: "+12025550123", priority: 3 },
  { id: "little-atlas", name: "Little Atlas Academy", neighborhood: "East Market", distanceMiles: 3.7, source: "Operator-provided directory", demoPhone: "+12025550124", priority: 4 },
  { id: "juniper-yard", name: "Juniper Yard Preschool", neighborhood: "Cedar Hill", distanceMiles: 4.2, source: "Operator-provided directory", demoPhone: "+12025550125", priority: 5 },
  { id: "hearthside", name: "Hearthside Children's Center", neighborhood: "West End", distanceMiles: 4.9, source: "Operator-provided directory", demoPhone: "+12025550126", priority: 6 },
];

export const fixtureResults: Record<string, CenterResult> = {
  "willow-room": {
    lineOutcome: "reached_staff",
    businessConfirmed: "yes",
    ageBandAccepted: "yes",
    vacancyStatus: "available",
    earliestStartDate: "2026-10-05",
    availableWeekdays: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    openingTime: "08:00",
    closingTime: "18:00",
    monthlyTuitionMinor: 142000,
    registrationFeeMinor: 7500,
    subsidyStatus: "accepted",
    tourStatus: "offered",
    tourWindows: ["Thursday at 10:00", "Friday at 15:30"],
    availabilityEvidence: "We have one toddler opening from October fifth.",
    scheduleEvidence: "That place is available Monday through Friday, eight to six.",
    feeEvidence: "Tuition is fourteen hundred and twenty dollars monthly, plus a seventy-five dollar registration fee.",
  },
  "alder-house": {
    lineOutcome: "reached_staff",
    businessConfirmed: "yes",
    ageBandAccepted: "yes",
    vacancyStatus: "available",
    earliestStartDate: "2026-10-12",
    availableWeekdays: ["monday", "wednesday", "friday"],
    openingTime: "07:30",
    closingTime: "17:45",
    monthlyTuitionMinor: 138000,
    registrationFeeMinor: 10000,
    subsidyStatus: "unknown",
    tourStatus: "offered",
    tourWindows: ["Wednesday at 09:30", "Thursday at 16:00"],
    availabilityEvidence: "A Monday, Wednesday, Friday toddler place opens October twelfth.",
    scheduleEvidence: "We open at seven thirty and close at five forty-five.",
    feeEvidence: "It is thirteen eighty per month and one hundred to register.",
  },
  "moss-and-moon": {
    lineOutcome: "reached_staff",
    businessConfirmed: "yes",
    ageBandAccepted: "yes",
    vacancyStatus: "waitlist",
    earliestStartDate: "",
    availableWeekdays: [],
    openingTime: "08:00",
    closingTime: "17:00",
    monthlyTuitionMinor: 129000,
    registrationFeeMinor: 5000,
    subsidyStatus: "accepted",
    tourStatus: "not_offered",
    tourWindows: [],
    availabilityEvidence: "There is no current toddler opening; the waitlist is about four months.",
    scheduleEvidence: "Our normal hours are eight until five.",
    feeEvidence: "The current toddler rate is twelve ninety per month.",
  },
  "little-atlas": {
    lineOutcome: "reached_staff",
    businessConfirmed: "yes",
    ageBandAccepted: "yes",
    vacancyStatus: "available",
    earliestStartDate: "2026-10-01",
    availableWeekdays: ["tuesday", "thursday"],
    openingTime: "08:00",
    closingTime: "18:00",
    monthlyTuitionMinor: 118000,
    registrationFeeMinor: 8500,
    subsidyStatus: "accepted",
    tourStatus: "offered",
    tourWindows: ["Tuesday at 11:00"],
    availabilityEvidence: "We have a toddler opening from October first for Tuesdays and Thursdays.",
    scheduleEvidence: "The open place is two days only, Tuesday and Thursday.",
    feeEvidence: "Monthly tuition is eleven hundred and eighty dollars.",
  },
  "juniper-yard": {
    lineOutcome: "reached_staff",
    businessConfirmed: "yes",
    ageBandAccepted: "yes",
    vacancyStatus: "full",
    earliestStartDate: "",
    availableWeekdays: [],
    openingTime: "07:30",
    closingTime: "18:00",
    monthlyTuitionMinor: -1,
    registrationFeeMinor: -1,
    subsidyStatus: "unknown",
    tourStatus: "not_offered",
    tourWindows: [],
    availabilityEvidence: "Our toddler room is full for the rest of this year.",
    scheduleEvidence: "",
    feeEvidence: "",
  },
  "hearthside": {
    lineOutcome: "reached_staff",
    businessConfirmed: "yes",
    ageBandAccepted: "yes",
    vacancyStatus: "available",
    earliestStartDate: "2026-10-13",
    availableWeekdays: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    openingTime: "08:00",
    closingTime: "18:30",
    monthlyTuitionMinor: 146000,
    registrationFeeMinor: 5000,
    subsidyStatus: "accepted",
    tourStatus: "offered",
    tourWindows: ["Monday at 14:00", "Wednesday at 10:30"],
    availabilityEvidence: "One toddler opening is available from October thirteenth.",
    scheduleEvidence: "It can cover all five weekdays from eight until six thirty.",
    feeEvidence: "The monthly fee is fourteen sixty, plus fifty dollars to register.",
  },
};

export const initialRecords: CenterCallRecord[] = fixtureCandidates.map((candidate, index) => ({
  candidateId: candidate.id,
  status: index < 3 ? "planned" : "held",
  result: null,
  source: "fixture",
}));

export const fixtureTourResult = {
  outcome: "confirmed",
  confirmedWindow: "Thursday at 10:00",
  nextStep: "Ask for Maya at reception and bring photo identification.",
  reference: "Tour with Maya",
  evidence: "I have you down for Thursday at ten. Please ask for Maya.",
};
