import {addDemoHistory} from './demo-history.mjs';
import {seedRecords,attachPatientContext,readPatientContext} from './records.mjs';
import {DRAFT_PROTOCOL,PHASES} from './protocol.mjs';
import {nextBreastQuestion,evaluateBreastRisk} from './risk.mjs';
import {nextContactWindow} from '../contact-time.mjs';
import {applyOutcome} from '../care-result.mjs';
export const DEMO_NOW='2026-09-12T14:00:00.000Z';
export const CLINICIAN={id:'demo-clinician',name:'Dr Sarah Chen',initials:'SC',role:'Breast care clinician',team:'Breast oncology',email:'sarah.chen@example.test'};
export const TASK_TYPES=Object.values(PHASES);
const specs=[['emma','Emma Wilson',48,'endocrine_therapy','endocrine','Left lumpectomy and sentinel node biopsy','2026-05-10','Tamoxifen','IIA','negative'],['nora','Nora Bennett',54,'post_op','stable','Left mastectomy','2026-09-03','Post-operative recovery plan','IIA','negative'],['olivia','Olivia Martin',45,'chemotherapy','emergency','Breast-conserving surgery','2026-07-15','Chemotherapy per oncology plan','IIB','negative'],['ellen','Ellen Brooks',61,'radiotherapy','skin','Right lumpectomy','2026-06-20','Radiotherapy per oncology plan','IA','negative'],['ava','Ava Thompson',57,'systemic_therapy','visit','Left lumpectomy','2026-04-18','HER2-directed treatment per oncology plan','IIA','positive'],['leah','Leah Patel',66,'survivorship','stable','Right lumpectomy','2023-02-10','Treatment completed','IA','negative']];
export function freshBreastCareOrders(){
 const patients=specs.map(([id,name,age,phase,demo_case,procedure,surgery_date,drug,stage,her2],i)=>({id:'bc-'+id,name,age,procedure,surgery_date,phone:'+120255501'+String(i+1).padStart(2,'0'),language:'English',region:'US',timezone:'America/New_York',contact_window:{start:8,end:20},contact_consent:true,auto_followup:true,authorization:{id:'demo-'+id,status:'ACTIVE',by:CLINICIAN.id,max_calls_per_order:2},consent_note:'Fictional patient consent for demo replay.',synthetic:true,revision:0,demo_case,oncology:{diagnosis:'Invasive breast carcinoma',stage,surgery:procedure,surgery_date,er:'positive',pr:'positive',her2,current_treatment:{phases:[phase],drug,start_date:phase==='endocrine_therapy'?'2026-07-01':phase==='post_op'?'2026-09-03':phase==='survivorship'?'2023-08-01':'2026-08-15',last_treatment:phase==='chemotherapy'?'2026-09-08':null,next_treatment:phase==='chemotherapy'?'2026-09-22':null},last_followup:{date:phase==='post_op'?'2026-09-07':phase==='endocrine_therapy'?'2026-08-01':'2026-09-01',issues:phase==='endocrine_therapy'?['Mild hot flashes','Occasional left arm tightness']:phase==='post_op'?['Incision dry at last contact; arm exercises underway']:phase==='radiotherapy'?['Mild redness in the treated skin without peeling']:['No new concerns reported at last contact']},next_visit:phase==='systemic_therapy'?'2026-09-10':'2026-11-01',planned_examinations:phase==='survivorship'?[{name:'Mammography already arranged by care team',due:'2026-11-01'}]:[],proxy_authorizations:[]}}));
 for(const p of patients)p.clinical_records=seedRecords(p);
 const tasks=patients.map((p,i)=>{const due_at=`2026-09-12T13:${String(i*8).padStart(2,'0')}:00.000Z`;const phase=p.oncology.current_treatment.phases[0];const instruction='Complete the breast cancer follow-up using the recorded treatment plan and hospital-approved protocol. Record changes, symptoms, treatment execution, appointments and patient concerns without changing treatment.';return {id:'followup-'+p.id,patient_id:p.id,patient:p.name,type:PHASES[phase],care_program:'breast',contact_reference_at:DEMO_NOW,task:PHASES[phase]+' review',due_at,due_time:due_at,status:'PENDING',revision:0,oncology_context:structuredClone(p.oncology),clinical_protocol:structuredClone(DRAFT_PROTOCOL),order:{instruction,author:CLINICIAN.name,due_at,created_at:'2026-09-11T14:00:00Z'},plan:{status:'READY',call_at:due_at,source:'Demo Simulation · recorded protocol contact',policy:'Illustrative contact from the recorded breast care plan.',purpose:'Identify changes and protocol flags requiring the care team.'},events:[]};});
 for(const t of tasks)attachPatientContext({patients,tasks,calls:[]},t,DEMO_NOW);
 return {version:5,replay_version:3,care_program:'breast',provider:'mock',patients,tasks,calls:[],reviews:[],audit_log:[],protocol:structuredClone(DRAFT_PROTOCOL),protocol_revision:0,demo_now:DEMO_NOW};
}
const yesno=value=>value==='yes'?'Yes.':'No.';
function symptomValue(name,field){const values={new:name==='hot_flash'?'no':'yes',onset:name==='hot_flash'?'Since starting treatment; worse this month':'7 days ago',duration:name==='hot_flash'?'A few minutes per episode':'Ongoing',severity:name==='hot_flash'?'moderate':'mild',trend:'worsening',frequency:'daily',associated:'No other associated symptoms reported',functional_impact:name==='hot_flash'?'yes':'no',red_flags:'no',side:'ipsilateral',distribution:'forearm',redness:'no',warmth:'no',pain:'yes',movement:'no',sleep_impact:'yes',location:'treated skin',at_rest:'no',missed_frequency:'2–3 times per week',reason:'forgot',description:'Redness and peeling in the treated skin',temperature_c:'39',last_treatment:'4 days ago',chills:'yes'};return values[field]||'unknown';}
function observationAnswer(code,person){
 const c=person.demo_case;
 if(code.startsWith('custom.')||code.startsWith('regimen.'))return {value:'unknown',text:"I'm not sure how to answer that."};
 if(code==='emergency.breathing'&&c==='emergency')return {value:'yes',text:"My chest really hurts... I can barely catch my breath. It's happening now."};
 if(code.startsWith('emergency.'))return {value:'no',text:"No, nothing like that right now."};
 if(code==='overall'&&c==='skin')return {value:'changed',text:"The skin where they do the radiation is redder, and it's started peeling. It wasn't peeling last time."};
 if(code==='overall'&&c==='visit')return {value:'stable',text:"Physically, about the same. But I think I got the appointment date wrong. Could we check that?"};
 if(code==='overall'&&person.id==='bc-nora')return {value:'stable',text:"Since the check on Monday, it's been about the same. The cut is dry. I'm doing the arm exercises they showed me."};
 if(code==='treatment.execution'&&c==='visit')return {value:'changed',text:"I haven't stopped treatment myself, but I missed the review on the tenth. I'm not sure what that means for the next treatment."};
 if(code==='systemic.regimen'&&c==='visit')return {value:'unknown',text:"I don't know if the next treatment has changed. I need the team to confirm it after that missed review."};
 if(code==='treatment.execution'&&person.id==='bc-leah')return {value:'as_planned',text:"I'm not having active treatment now. I've kept the follow-up appointments so far."};
 if(code==='post_op.rehab')return {value:'as_planned',text:"Yes, I've been doing the movements from the sheet they gave me. I can manage those."};
 if(code==='radio.attendance')return {value:'as_planned',text:"I've been to the sessions as arranged. I haven't canceled any because of the skin."};
 if(code==='endocrine.adherence')return {value:'as_planned',text:"I'm still taking the tamoxifen as prescribed. I haven't missed any tablets."};
 if(code==='qol.impact')return c==='endocrine'?{value:'yes',text:"Eating's okay, and I can do my usual stuff. It's the nights, really. Those hot flashes keep waking me up."}:{value:'no',text:"I'm sleeping and eating okay, and managing my usual activities. Nothing else has been troubling me."};
 if(code==='screen.persistent_symptoms'&&(c==='endocrine'||c==='skin'))return {value:'no',text:"Nothing else apart from what we just talked about."};
 if(code==='overall'&&c==='endocrine')return {value:'changed',text:"Mostly okay, I guess. But those hot flashes... they're waking me up now. And this left arm looks puffy. It used to feel tight, but the swelling is new.",symptoms:['hot_flash','arm_swelling']};
 if(code==='radio.skin'&&c==='skin')return {value:'yes',text:"It's kind of red where they do the treatment, and the skin's peeling a bit. More than last week, actually.",symptoms:['other']};
 if(code==='visits.plan'&&c==='visit')return {value:'changed',text:"I thought it was next week. Hang on... no, you're right, it was the tenth. I missed it, and I haven't booked another one.",extra:{code:'visits.overdue',value:'yes'}};
 if(code==='visits.attended')return {value:c==='visit'?'no':'yes',text:c==='visit'?'No, I did not attend that visit.':'Yes, I attended the recorded visit.'};
 if(code==='overall')return {value:'stable',text:"Pretty much the same as last time, honestly. Nothing new, and nothing's getting worse."};
 if(code.includes('adherence')||code==='treatment.execution'||code.includes('attendance')||code.includes('regimen')||code.includes('cycle')||code.includes('rehab'))return {value:'as_planned',text:"Yeah, I've stuck with what the team told me. Haven't missed anything or changed it myself."};
 if(code.startsWith('visits.')||code==='survivorship.screening')return {value:'as_planned',text:"Yeah, those are still in my calendar. No changes to what the team arranged."};
 if(code==='endocrine.effects'&&c==='endocrine')return {value:'changed',text:"It's those hot flashes I mentioned. More of them, and they're messing with my sleep."};
 return {value:'no',text:"No, I haven't noticed any of that."};
}
function naturalSymptomAnswer(name,field,value){
 const statements={onset:name==='hot_flash'?"Since I started treatment, but this month has been worse.":"About a week ago, I think.",duration:name==='hot_flash'?"A few minutes each time, then it passes. But it keeps happening again.":"It hasn't really gone away.",severity:value==='moderate'?"Somewhere in the middle. Not the worst, but it bothers me.":"Not too bad. I'd call it mild.",trend:"It's getting worse, I'd say.",frequency:"Pretty much every day.",associated:"Nothing else that I've noticed.",functional_impact:value==='yes'?"Yes, it's interrupting my sleep.":"No, I can still sleep, eat and do my usual things.",new:value==='yes'?"Yes, that's new since we last spoke.":"No, I've had it before. It's changed, though.",red_flags:"No, no trouble breathing or fainting or anything like that.",side:"Same side as my surgery.",distribution:"Mostly here in my forearm.",redness:"No, the colour looks normal.",warmth:"No, it doesn't feel hotter.",pain:"Yeah, it aches a little.",movement:"No, I can still move it normally.",sleep_impact:"Yes, it wakes me up in the night.",description:"The skin's red and there's some peeling where they do the treatment.",location:"Where they're treating the skin."};return statements[field]||(['yes','no'].includes(value)?yesno(value):value);
}
function reportRecap(report,risk,person){
 const observations=report.oncology.observations,parts=[];
 const fact=code=>observations.find(f=>f.code===code);
 if(fact('endocrine.adherence')?.value==='as_planned')parts.push(`You said you are taking ${person.oncology.current_treatment.drug} as prescribed without missed doses.`);
 for(const symptom of report.oncology.symptoms){const f=code=>symptom.facts.find(v=>v.code===code);const name=symptom.name==='other'?(f('description')?.value||'the skin changes'):symptom.name.replaceAll('_',' ');parts.push(`You described ${name}${f('trend')?.value==='worsening'?' getting worse':''}${f('sleep_impact')?.value==='yes'?', affecting your sleep':''}.`);if(symptom.name==='arm_swelling'&&f('onset')?.value==='7 days ago')parts.push('You clarified that the swelling started about a week ago.');}
 if(fact('visits.attended')?.value==='no'||fact('visits.plan')?.value==='changed')parts.push('You reported missing the arranged review and needing to rearrange it.');
 if(fact('systemic.regimen')?.value==='unknown')parts.push('The next treatment schedule still needs confirmation with your care team.');
 if(!parts.length&&fact('overall')?.value==='stable')parts.push('You reported no new or worsening physical concerns since the last contact.');
 if(risk.missing.length)parts.push('Some details remain uncertain and need to be checked.');
 if(!parts.length)parts.push('I have recorded the answers you were able to give.');
 return parts.join(' ');
}
export function simulateBreastCall(task,person,protocol=DRAFT_PROTOCOL){
 person={...person,demo_case:person.demo_case||'unestablished',reference_at:task.contact_reference_at||DEMO_NOW};
 const turns=[];const add=(speaker,text)=>{const e={quote:text,turn_index:turns.length};turns.push({speaker,text});return e;};
 add('agent',`Hello, I am Avelis, the automated follow-up assistant for your breast care team. May I confirm I am speaking with ${person.name}?`);const identity=add('patient',`Yes, this is ${person.name}.`);
 add('agent','Is now a good time for a short follow-up?');add('patient',person.id==='bc-nora'?"Hang on, let me turn the TV down... okay, I'm here.":"Yeah, I've got a few minutes.");add('agent','Your answers will be recorded for the care team. Do you agree to continue?');const consent=add('patient',"Yes, that's okay.");
 const report={schema_version:'3',conversation:{identity:'confirmed',identity_evidence:[identity],consent:'agreed',consent_evidence:[consent],ending:'completed'},instruction_results:[],patient_reports:[],patient_requests:[],open_questions:[],contact_preference:{agreement_state:'none',wording:'',at:'',evidence:[],proposal_evidence:[]},review:{required:false,reason:'',questions:[],evidence:[]},care_summary:'',oncology:{respondent:'patient',proxy_name:'',phase_report:'consistent',observations:[],symptoms:[],limitations:[]}};
 const trace=[];
 for(let i=0;i<80;i++){
  const step=nextBreastQuestion(report,person,protocol);trace.push({node:step.node,topic:step.symptom?step.symptom+'.'+step.code:step.code||null,turn_index:turns.length,risk:evaluateBreastRisk(report,person,protocol,{verified:true}).level});
  if(step.node==='EMERGENCY_HANDOFF'){add('agent',"I’m stopping the routine questions because you’ve described severe chest pain and difficulty breathing. Please call your local emergency number now. This call cannot dispatch emergency help.");report.oncology.limitations.push('Routine follow-up stopped at the emergency gate.');break;}
  if(step.node==='SUMMARY')break;
  let question=step.question;if(step.symptom==='other')question=question.replaceAll('this other','this skin change').replaceAll('the other','the skin change');if(step.code==='overall'&&person.oncology.last_followup.issues.length)question=`At your last contact you reported ${person.oncology.last_followup.issues.join(' and ')}. How has that changed, and is anything new or getting worse?`;
  if(step.code==='visits.plan')question=person.oncology.next_visit<person.reference_at.slice(0,10)?`Your care team recorded a visit for ${person.oncology.next_visit}. Did you attend, or does it still need to be rearranged?`:`Your care team recorded the next visit for ${person.oncology.next_visit}. Is it still arranged, or has the plan changed?`;
  add('agent',question);
  if(person.id==='bc-nora'&&step.code==='overall'){add('patient',"Sorry, you went quiet for a second. Could you say that again?");add('agent',"Of course. Since we last spoke, has anything new come up or started getting worse?");}
  if(person.id==='bc-ellen'&&step.code==='radio.skin'){add('patient',"Do you mean where they do the radiation, or my surgery scar?");add('agent',"The area receiving radiation. What have you noticed there?");}
  if(person.id==='bc-leah'&&step.code==='screen.persistent_symptoms'){add('patient',"Sorry, that was a lot at once. What was the question?");add('agent',"Have you noticed any new symptoms that keep coming back or are getting worse? You can describe them in your own words.");}

  if(step.symptom){const value=person.id==='bc-ellen'&&step.code==='onset'?'unknown':symptomValue(step.symptom,step.code);let text=value==='unknown'?"I can't really pin it down, sorry. Maybe last week, maybe earlier.":naturalSymptomAnswer(step.symptom,step.code,value);
  if(step.symptom==='arm_swelling'&&step.code==='onset'){add('patient',"Maybe three days? Actually, no... it was already puffy last Saturday.");add('agent',"So around a week, rather than three days?");text="Yes, about a week. Sorry, I got the days mixed up.";}
  if(step.symptom==='arm_swelling'&&step.code==='side'){add('patient',"The right—sorry, the left. I always mix them up on the phone.");add('agent',"Your left arm, on the side of the breast surgery?");text="Yes, left arm, same side as the surgery.";}
  const evidence=add('patient',text);report.oncology.symptoms.find(s=>s.name===step.symptom).facts.push({code:step.code,value,detail:text,evidence:[evidence]});}
  else{const answer=observationAnswer(step.code,person);const evidence=add('patient',answer.text);report.oncology.observations.push({code:step.code,value:answer.value,detail:answer.text,evidence:[evidence]});if(answer.extra)report.oncology.observations.push({...answer.extra,detail:answer.text,evidence:[evidence]});for(const name of answer.symptoms||[])if(!report.oncology.symptoms.some(s=>s.name===name)){const facts=[];if(name==='hot_flash')for(const code of ['functional_impact','sleep_impact'])facts.push({code,value:'yes',detail:answer.text,evidence:[evidence]});if(name==='other'&&step.code==='radio.skin'){facts.push({code:'description',value:'Redness and peeling in the treated skin',detail:answer.text,evidence:[evidence]});facts.push({code:'trend',value:'worsening',detail:answer.text,evidence:[evidence]});}report.oncology.symptoms.push({name,facts});}}
 }
 const risk=evaluateBreastRisk(report,person,protocol,{verified:true,complete:true});
 const clinical=['RED','YELLOW'].includes(risk.level);const evidence=risk.triggers.flatMap(t=>t.evidence).slice(0,4);
 report.care_summary=risk.level==='RED'?'Patient reported severe chest pain and severe breathing difficulty. Routine questions stopped. Emergency help was advised; receipt of help has not been confirmed.':reportRecap(report,risk,person).replaceAll('You said you are','Patient reports').replaceAll('You described','Patient describes').replaceAll('You clarified','Patient clarified').replaceAll('You reported','Patient reported').replaceAll('your sleep','sleep').replaceAll('your care team','the care team')+(clinical?' Care-team review is required.':risk.level==='GREEN'?' Continue the recorded routine follow-up plan.':' Information requires verification.');
 report.review={required:clinical,reason:risk.triggers.map(t=>t.label).join('; '),questions:clinical?['Review the reported changes and determine the next action under the hospital SOP.']:[],evidence};
 const groups=[['changes',['overall']],['symptoms',['overall','screen.persistent_symptoms','screen.breast_change']],['treatment execution',['treatment.execution']],['appointments',['visits.plan','visits.attended']],['patient concerns',['qol.impact']]];
 report.instruction_results=groups.filter(([quote])=>task.order.instruction.includes(quote)).map(([quote,codes])=>{const facts=[...report.oncology.observations.filter(f=>codes.includes(f.code)),...(['changes','symptoms'].includes(quote)?report.oncology.symptoms.flatMap(s=>s.facts.map(f=>({...f,detail:s.name+' / '+f.code+': '+f.detail}))):[])];return {order_quote:quote,question:'Record '+quote,completion_state:facts.length?'completed':'not_asked',finding:facts.length?facts.map(f=>f.detail).join(' '):'Not assessed before the conversation ended.',evidence:facts.flatMap(f=>f.evidence)};});
 if(!report.instruction_results.length)report.instruction_results=[{order_quote:task.order.instruction,question:'Instruction coverage',completion_state:'unclear',finding:'This authored replay does not establish all requirements of a custom instruction.',evidence:[]}];
 if(risk.level!=='RED'){add('agent',reportRecap(report,risk,person)+' Have I got that right, or is there something to change?');add('patient',"Yeah, you've got it. That's what I meant.");add('agent',clinical?protocol.clinician_text:'The next routine contact follows the recorded care-team plan. Medication instructions are unchanged.');}
 return {report,transcript:turns.map(t=>(t.speaker==='patient'?'Patient: ':'Agent: ')+t.text).join('\n'),trace,risk};
}
export function scheduleRoutine(db,task,call,person,now,mode='demo'){
 person=db.patients.find(p=>p.id===task.patient_id)||person;
 if(call.routing!=='COMPLETED'||call.risk_assessment?.level!=='GREEN'||db.tasks.some(t=>t.previous_task_id===task.id))return;
 const protocol=db.protocol||DRAFT_PROTOCOL;const days=Math.min(...person.oncology.current_treatment.phases.map(p=>protocol.routine_days[p]));if(!Number.isFinite(days)||days<1)return;
 const at=nextContactWindow(Date.parse(now)+days*86400000,person);const id='routine-'+call.id;
 const next={id,previous_task_id:task.id,patient_id:task.patient_id,patient:task.patient,type:task.type,care_program:'breast',task:task.task,due_at:at,due_time:at,revision:0,status:'PENDING',order:{...task.order,due_at:at},oncology_context:structuredClone(person.oncology),clinical_protocol:structuredClone(protocol),prior_findings:call.conversation_report,plan:{status:mode==='demo'?'READY':'NEEDS_PLAN',timezone:person.timezone,call_at:at,not_before:at,source:'Doctor-configured protocol · '+(protocol.review_state==='DRAFT'?'Demo draft':'Approved'),policy:`Routine contact interval: ${days} days in the recorded protocol.`,purpose:'Compare with this follow-up and check for changes.'},events:[{at:now,label:'Routine follow-up planned',detail:'From the recorded protocol, not a model-invented clinical interval.'}]};db.tasks.push(next);call.next_contact_plan={...next.plan};
}
export function runBreastDueWork(snapshot,now=DEMO_NOW,onlyTaskId=null){const db=structuredClone(snapshot);db.demo_now=now;for(const task of [...db.tasks]){if(onlyTaskId&&task.id!==onlyTaskId)continue;if(task.call_id||task.status==='COMPLETED'||task.safety_hold||!['READY','ACTIVE'].includes(task.plan?.status)||Date.parse(task.plan.call_at)>Date.parse(now))continue;const p=db.patients.find(p=>p.id===task.patient_id);if(!p?.auto_followup||!p.contact_consent||p.safety_hold)continue;task.contact_reference_at=now;const context=attachPatientContext(db,task,now);if(context.conflicts.length){task.status='UNRESOLVED';task.plan.status='WAITING_CLINICIAN';task.plan.policy='Conflicting patient records require review before contact.';continue;}const simulation=simulateBreastCall(task,p,db.protocol);task.clinical_protocol=structuredClone(db.protocol);task.oncology_context=structuredClone(p.oncology);const call={id:'call-'+task.id,task_id:task.id,provider:'mock',state:'FINISHED',status:'COMPLETED',created_at:task.plan.call_at,updated_at:new Date(Date.parse(task.plan.call_at)+120000).toISOString(),transcript:simulation.transcript,recording_url:null,initiated_by:'AUTOMATED_FOLLOWUP',protocol_trace:simulation.trace};task.call_id=call.id;db.calls.push(call);applyOutcome(db,call,{status:'COMPLETED',result:{transcript:simulation.transcript,extracted:{conversation_result:simulation.report}}},{supported:!task.custom_demo_order,coverage_complete:simulation.risk.level!=='RED',identity_valid:true,consent_valid:true,needs_review:!!task.custom_demo_order,stop_contact:false,contact_agreement_valid:false,issues:task.custom_demo_order?['Simulated answers do not establish completion of this custom care instruction. Verify with the patient.']:[],source:'Demo Simulation · scripted facts'});if(!call.next_contact_plan&&call.routing!=='COMPLETED')call.next_contact_plan={status:'WAITING_CLINICIAN',call_at:null,policy:'Care-team review is required before further automatic contact. Local review queue only; no external alert sent.'};task.events.push({at:call.created_at,label:'Protocol-led follow-up',call_record_id:call.id,detail:p.oncology.current_treatment.phases.map(x=>PHASES[x]).join(' + ')});task.events.push({at:call.updated_at,label:'Rule engine: '+call.risk_assessment?.level,call_record_id:call.id,detail:call.result.summary});scheduleRoutine(db,task,call,p,call.updated_at);}
 return db;}
export function freshBreastWorkspace(){return runBreastDueWork(addDemoHistory(freshBreastCareOrders()));}
export function addBreastOrder(snapshot,input){const db=structuredClone(snapshot),p=db.patients.find(p=>p.id===input.patient_id);if(!p?.oncology||!TASK_TYPES.includes(input.type)||!input.task?.trim()||!input.instruction?.trim()||!Number.isFinite(Date.parse(input.due_at))||Date.parse(input.due_at)<=Date.parse(db.demo_now))throw Error('Choose a breast care patient, follow-up type, original instruction and future contact date.');if(db.tasks.some(t=>t.id===input.id))return db;db.tasks.push({id:input.id,patient_id:p.id,patient:p.name,type:input.type,care_program:'breast',task:input.task,order:{instruction:input.instruction,due_at:input.due_at,author:CLINICIAN.name},due_at:input.due_at,due_time:input.due_at,status:'PENDING',revision:0,oncology_context:structuredClone(p.oncology),clinical_protocol:structuredClone(db.protocol),plan:{status:p.auto_followup?'READY':'CONTACT_PAUSED',call_at:nextContactWindow(input.due_at,p),source:'Demo Simulation · clinician-recorded contact',policy:'Contact date supplied in the care plan.'},events:[{at:db.demo_now,label:'Care instruction recorded',detail:'Original clinician instruction preserved.'}]});const added=db.tasks.at(-1);const context=attachPatientContext(db,added,db.demo_now);if(context.conflicts.length)added.plan={status:'WAITING_CLINICIAN',call_at:null,policy:'Conflicting patient records require review.'};return db;}
export function freshBreastLive(now=new Date().toISOString()){const db=freshBreastCareOrders();db.provider='calle';db.demo_now=now;for(const p of db.patients){p.phone='';p.auto_followup=false;p.contact_consent=false;p.authorization=null;p.consent_note='';delete p.demo_case;}for(const t of db.tasks)t.plan={status:'CONTACT_PAUSED',call_at:null,policy:'Record consent and complete hospital protocol review before live follow-up.'};return db;}
