"use client";
import { useEffect, useState } from "react";
import Link from "next/link";

const sources = ["Direct observation", "Personal action", "Document reference", "Hearsay", "Assumption", "Unknown"];
const certainty = ["Confirmed", "Probable", "Uncertain", "Not known"];

export default function HumanInterviewWorkspace({ taskId }: { taskId: string }) {
  const [task, setTask] = useState<{ summary: string; assignee?: string; due_at?: string } | null>(null);
  const [state, setState] = useState<"loading" | "ready" | "submitted" | "error">("loading");
  const [message, setMessage] = useState("");
  const [form, setForm] = useState({ interviewer: "Jordan Patel, Environmental Professional", method: "Phone", interview_date: "2026-08-26T10:00", respondent_name: "Morgan Lee", respondent_role: "Former property manager", knowledge_start: "1991", knowledge_end: "1996", operations_answer: "", operations_source: "Direct observation", operations_confidence: "Confirmed", storage_answer: "", storage_source: "Direct observation", storage_confidence: "Uncertain", limitations: "", declined_notes: "", confirmed: false });
  useEffect(() => { fetch(`/api/human-interview?task_id=${encodeURIComponent(taskId)}`).then(async (response) => ({ ok: response.ok, data: await response.json() })).then(({ ok, data }) => { if (!ok) throw new Error(data.error); setTask(data.task); setState(data.submitted ? "submitted" : "ready"); if (data.submitted) setMessage(`Interview record submitted ${new Date(data.submitted_at).toLocaleString()}.`); }).catch((error) => { setMessage(error.message || "Task unavailable."); setState("error"); }); }, [taskId]);
  const update = (key: string, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async () => { setMessage(""); const response = await fetch("/api/human-interview", { method: "POST", headers: { "content-type": "application/json", "x-demo-role": "coordinator" }, body: JSON.stringify({ task_id: taskId, ...form }) }); const data = (await response.json()) as { error?: string; submitted_at?: string }; if (!response.ok) { setMessage(data.error || "Interview could not be submitted."); return; } setState("submitted"); setMessage(`Interview record submitted ${new Date(data.submitted_at!).toLocaleString()}.`); };
  if (state === "loading") return <main className="respondentPage"><p>Opening interview workspace…</p></main>;
  if (state === "error") return <main className="respondentPage"><section className="respondentCard"><h1>Task unavailable</h1><p>{message}</p></section></main>;
  if (state === "submitted") return <main className="respondentPage"><section className="respondentCard submittedCard"><span className="submissionCheck">✓</span><p className="eyebrow">INTERVIEW RECORD RECEIVED</p><h1>Ready for EP review.</h1><p>{message}</p><p>The original human-interview record is preserved, and two source-linked statements are pending professional review.</p><Link className="returnLink" href="/case-file">Return to SiteWitness</Link></section></main>;
  return <main className="respondentPage humanWorkspace"><header className="respondentHeader"><span className="brandMark">SW</span><div><strong>SiteWitness</strong><small>Human interview workspace</small></div></header><section className="respondentCard">
    <p className="eyebrow">47 BAKER STREET · COORDINATOR RECORD</p><h1>Conduct the bounded interview</h1><p className="respondentIntro">Record the respondent’s factual answers faithfully. Do not ask for environmental conclusions, liability opinions, cleanup costs, or recommendations.</p>
    <div className="requestScope"><strong>Assigned scope</strong><p>{task?.summary}</p><small>{task?.assignee}{task?.due_at ? ` · Scheduled ${new Date(task.due_at).toLocaleString()}` : ""}</small></div>
    <fieldset><legend>Interview details</legend><div className="formPair"><label>Interviewer<input value={form.interviewer} onChange={(e) => update("interviewer", e.target.value)} /></label><label>Method<select value={form.method} onChange={(e) => update("method", e.target.value)}><option>Phone</option><option>Video</option><option>In person</option></select></label></div><label className="wideLabel">Interview date and time<input type="datetime-local" value={form.interview_date} onChange={(e) => update("interview_date", e.target.value)} /></label></fieldset>
    <fieldset><legend>Respondent and knowledge period</legend><div className="formPair"><label>Respondent name<input value={form.respondent_name} onChange={(e) => update("respondent_name", e.target.value)} /></label><label>Role at property<input value={form.respondent_role} onChange={(e) => update("respondent_role", e.target.value)} /></label></div><div className="formPair"><label>Knowledge began<input type="number" value={form.knowledge_start} onChange={(e) => update("knowledge_start", e.target.value)} /></label><label>Knowledge ended<input type="number" value={form.knowledge_end} onChange={(e) => update("knowledge_end", e.target.value)} /></label></div></fieldset>
    <InterviewQuestion number="01" title="Operations before 1991" prompt="What, if anything, do you personally know about garment-cleaning operations at 47 Baker Street before 1991?" answer={form.operations_answer} source={form.operations_source} confidence={form.operations_confidence} update={update} answerKey="operations_answer" sourceKey="operations_source" confidenceKey="operations_confidence" />
    <InterviewQuestion number="02" title="Rear storage room" prompt="What, if anything, did you personally observe about the use or contents of the rear storage room?" answer={form.storage_answer} source={form.storage_source} confidence={form.storage_confidence} update={update} answerKey="storage_answer" sourceKey="storage_source" confidenceKey="storage_confidence" />
    <label className="wideLabel">Knowledge limitations<textarea value={form.limitations} onChange={(e) => update("limitations", e.target.value)} placeholder="Areas not accessed, dates not known, or second-hand information." /></label><label className="wideLabel">Declined or unanswered questions<textarea value={form.declined_notes} onChange={(e) => update("declined_notes", e.target.value)} placeholder="Record any question the respondent declined or could not answer." /></label>
    <label className="respondentAck"><input aria-label="Confirm interview record accuracy" type="checkbox" checked={form.confirmed} onChange={(e) => update("confirmed", e.target.checked)} /><span><strong>I confirm this record accurately reflects the human-led interview.</strong><small>The respondent’s original answers will be preserved and reviewed by an Environmental Professional.</small></span></label>
    {message && <div className="formError" role="alert">{message}</div>}<button className="primary respondentSubmit" disabled={!form.confirmed} onClick={submit}>Submit interview record <span>→</span></button>
  </section></main>;
}

function InterviewQuestion(p: { number: string; title: string; prompt: string; answer: string; source: string; confidence: string; answerKey: string; sourceKey: string; confidenceKey: string; update: (key: string, value: string) => void }) {
  return <fieldset className="responseQuestion"><legend><span>{p.number}</span>{p.title}</legend><p>{p.prompt}</p><label>Respondent’s answer<textarea value={p.answer} onChange={(e) => p.update(p.answerKey, e.target.value)} /></label><div className="formPair"><label>Basis of answer<select value={p.source} onChange={(e) => p.update(p.sourceKey, e.target.value)}>{sources.map((x) => <option key={x}>{x}</option>)}</select></label><label>Certainty<select value={p.confidence} onChange={(e) => p.update(p.confidenceKey, e.target.value)}>{certainty.map((x) => <option key={x}>{x}</option>)}</select></label></div></fieldset>;
}
