#!/usr/bin/env python3
"""Write a committable record of the calls this project has actually placed.

Checkpoints under `.call-state/` are the only durable proof that a call was
dialled: they are written before `create` and survive a wiped ledger. They are
not committable as they stand, because each one carries a partially masked
phone number and a hash derived from the live API key, which is also the
directory name.

This reduces them to the part that is safe to publish and useful to a reviewer:
which calls were placed, for which shop, and how they ended. Run it after a
live call and commit the result.

    python3 calls_placed.py            # print
    python3 calls_placed.py --write    # update CALLS.md
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
STATE = ROOT / ".call-state"
OUT = ROOT / "CALLS.md"

# Everything not listed here stays out. An allowlist, so a field added to the
# checkpoint later cannot leak by default.
SAFE_FIELDS = ("call_id", "idempotency_key", "phase", "status", "updated_at")


def checkpoints() -> list[dict]:
    if not STATE.is_dir():
        return []
    found = []
    for path in sorted(STATE.rglob("*.json")):
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        if isinstance(payload, dict):
            found.append({k: payload.get(k) for k in SAFE_FIELDS})
    return found


def placed(records: list[dict]) -> list[dict]:
    """Only calls CALL-E actually created. A `reserved` checkpoint with no
    call id means the attempt never got that far, and claiming otherwise would
    overstate what this project has done."""
    return [r for r in records if r.get("call_id")]


def slot(key: str | None) -> tuple[str, str, str]:
    """shopvoice-{shop}-{type}-{YYYY}-{MM}-{DD}[-r{n}] -> shop, type, date.

    A shop id may itself contain dashes, so the date is peeled off the right
    where its shape is known, and the call type is what remains at the end.
    """
    if not key or not key.startswith("shopvoice-"):
        return ("?", "?", "?")
    body = key[len("shopvoice-"):]

    attempt = body.rsplit("-", 1)
    if len(attempt) == 2 and attempt[1].startswith("r") and attempt[1][1:].isdigit():
        body = attempt[0]

    parts = body.rsplit("-", 3)
    if len(parts) < 4:
        return (body, "?", "?")
    head, y, m, d = parts
    shop, _, call_type = head.rpartition("-")
    return (shop or head, call_type or "?", f"{y}-{m}-{d}")


def render(records: list[dict]) -> str:
    done = placed(records)
    lines = [
        "# Calls placed",
        "",
        "Generated by `calls_placed.py` from the local checkpoints. Phone",
        "numbers and the account hash are deliberately not included.",
        "",
    ]
    if not done:
        lines += ["No calls have been placed from this checkout yet.", ""]
        return "\n".join(lines)

    lines += [
        f"{len(done)} call{'s' if len(done) != 1 else ''} placed.",
        "",
        "| Call ID | Shop | Type | Ledger date | Status |",
        "| --- | --- | --- | --- | --- |",
    ]
    for r in sorted(done, key=lambda x: x.get("updated_at") or ""):
        shop, call_type, day = slot(r.get("idempotency_key"))
        lines.append(
            f"| `{r['call_id']}` | {shop} | {call_type} | {day} | "
            f"{r.get('status') or r.get('phase') or 'unknown'} |"
        )
    lines.append("")

    abandoned = len(records) - len(done)
    if abandoned:
        lines += [
            f"{abandoned} checkpoint{'s' if abandoned != 1 else ''} recorded an "
            "attempt that CALL-E never created, so no call was placed for "
            "those and they are not listed.",
            "",
        ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--write", action="store_true",
                        help=f"write {OUT.name} instead of printing")
    args = parser.parse_args()

    text = render(checkpoints())
    if args.write:
        OUT.write_text(text, encoding="utf-8")
        print(f"wrote {OUT.relative_to(ROOT)}")
    else:
        print(text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
