import { Badge } from "@/components/ui/badge";

/**
 * What a figure is worth, said on the figure.
 *
 * Every number in this catalogue was one of two things and looked like the
 * same thing: hand-written at the start of the project, or generated by
 * lib/profile-gen.ts. Not one recorded where it came from. The rule now is
 * that a figure carries its own standing, and there are exactly three:
 *
 *   estimate   nobody's number. Ours, or generated. Useful, not authoritative.
 *   sourced    a citation exists and can be named.
 *   confirmed  someone said it on a call and agreed to it when it was read
 *              back. This is the only one that is evidence, and it is the
 *              product's entire argument.
 *
 * One component so the three cannot drift apart across five screens.
 */
export type ProvenanceKind = "estimate" | "sourced" | "confirmed";

export function provenanceLabel(kind: ProvenanceKind): string {
  switch (kind) {
    case "estimate": return "estimate — not sourced";
    case "sourced": return "sourced";
    case "confirmed": return "confirmed on the call";
  }
}

export function ProvenanceChip({
  kind,
  note,
  className,
}: {
  kind: ProvenanceKind;
  /** The citation, for `sourced`. Shown on hover rather than inline: it is
   *  provenance, not a headline. */
  note?: string | null;
  className?: string;
}) {
  const variant = kind === "confirmed" ? "lilac" : kind === "sourced" ? "outline" : "muted";
  return (
    <Badge variant={variant} className={className} title={note ?? undefined}>
      {provenanceLabel(kind)}
    </Badge>
  );
}

/**
 * The line that is the whole argument: what we guessed, what they said.
 *
 *   estimate PKR 8,000 -> confirmed PKR 7,000   heard here
 *
 * Both stay. Replacing the estimate with the confirmed figure would hide the
 * only evidence that calling them was worth doing.
 */
export function EstimateToConfirmed({
  estimatePkr,
  confirmedPkr,
  currency = "PKR",
}: {
  estimatePkr: number | null | undefined;
  confirmedPkr: number | null | undefined;
  currency?: string;
}) {
  if (confirmedPkr == null) return null;
  return (
    <span className="flex flex-wrap items-baseline gap-1.5">
      {estimatePkr != null && estimatePkr !== confirmedPkr && (
        <>
          <span className="text-small text-text-muted line-through">
            {currency} {estimatePkr.toLocaleString()}
          </span>
          <span aria-hidden className="text-small text-text-muted">→</span>
        </>
      )}
      <span className="type-data text-text">{currency} {confirmedPkr.toLocaleString()}</span>
    </span>
  );
}
