type Scalar = string | number | boolean;
export type SiteKey = "dry_cleaner" | "gas_station" | "auto_repair";
export type GoalPlan = { goalFamily: string; property: string; assessmentId: string; evidenceGap: string; knownRecords: string; respondentRole: string; expectedKnowledgePeriod: string; priorityBranches: string[]; completionConditions: string[]; prohibitedConclusions: string[]; escalationRoute: string };
const prohibitions = ["Recognized environmental condition", "Phase II recommendation", "Contamination or liability conclusion", "Remediation or legal advice"];
const sites: Record<SiteKey, { variables: Record<string, Scalar>; branches: string[] }> = {
  dry_cleaner: { variables: { property_address: "47 Baker Street", assessment_id: "ESA-0047", historical_use: "Sparkle Cleaners listed from 1987 through 1994", relevant_years: "1987-1994", evidence_gap: "Determine whether onsite dry cleaning occurred and bound the respondent's personal knowledge period", known_records: "Historical directory; owner questionnaire says 'I believe it was only a drop shop'", questionnaire_answer: "I believe it was only a drop shop", respondent_role: "Property manager", expected_knowledge_period: "1991-1996", domain_pack: "dry_cleaner_historical_use", prohibited_conclusions: "No REC, Phase II, liability, contamination, remediation, or legal conclusion" }, branches: ["Verify role and personal-knowledge period", "Distinguish personal observation from the phrase ‘drop shop’", "Ask about machinery, solvent, drums, drains, deliveries, and waste only where access supports it", "Bound rear, storage, and mechanical-area access", "Identify prior managers or archived tenant records"] },
  gas_station: { variables: { property_address: "Synthetic 73 Market Road", assessment_id: "ESA-0073", historical_use: "Former gasoline station shown in historical records", relevant_years: "1974-1992", evidence_gap: "Bound first-hand knowledge of underground tanks, removal, and closure records", known_records: "Historical maps and an unverified statement that tanks were removed", questionnaire_answer: "I think the tanks were removed around 1992", respondent_role: "Former operator", expected_knowledge_period: "1988-1994", domain_pack: "gas_station_tank_history", prohibited_conclusions: "No REC, Phase II, liability, contamination, remediation, or legal conclusion" }, branches: ["Separate observed tank work from hearsay", "Preserve approximate removal dates", "Ask about closure records and agencies", "Identify contractors or prior operators"] },
  auto_repair: { variables: { property_address: "812 Fulton Avenue", assessment_id: "ESA-0812", historical_use: "Former auto-repair operation", relevant_years: "1998-2012", evidence_gap: "Bound first-hand knowledge of parts washing, oil handling, drains, sumps, and waste contractors", known_records: "Directory and questionnaire provide conflicting descriptions of vehicle maintenance", questionnaire_answer: "We only did minor repairs", respondent_role: "Former shop supervisor", expected_knowledge_period: "2003-2010", domain_pack: "auto_repair_historical_use", prohibited_conclusions: "No REC, Phase II, liability, contamination, remediation, or legal conclusion" }, branches: ["Clarify what ‘minor repairs’ means", "Ask about parts washers and solvents", "Bound drain and sump access", "Identify oil and waste contractors", "Separate personally observed facts from shop-wide assumptions"] },
};
export function compileGoalContext(siteKey: SiteKey) {
  const site = sites[siteKey];
  if (!site) throw new Error("Unsupported SiteWitness Goal family.");
  for (const value of Object.values(site.variables)) { if (!["string", "number", "boolean"].includes(typeof value)) throw new Error("Goal Run variables must be finite JSON scalars."); if (typeof value === "string" && value.length > 1500) throw new Error("Goal Run variable exceeds the disclosure budget."); }
  const source = site.variables;
  const variables = { property: String(source.property_address), domain_type: String(source.domain_pack), evidence_gap: String(source.evidence_gap), known_records: String(source.known_records), relevant_years: String(source.relevant_years), respondent_role: String(source.respondent_role) };
  const plan: GoalPlan = { goalFamily: String(source.domain_pack), property: String(source.property_address), assessmentId: String(source.assessment_id), evidenceGap: String(source.evidence_gap), knownRecords: String(source.known_records), respondentRole: String(source.respondent_role), expectedKnowledgePeriod: String(source.expected_knowledge_period), priorityBranches: [...site.branches], completionConditions: ["Resolve or bound the factual gap with supported evidence", "Preserve unknowns, hearsay, uncertainty, and access limits", "Escalate a decline, contradiction, sensitive fact, or human request"], prohibitedConclusions: prohibitions, escalationRoute: "Return to the SiteWitness Coordinator for human follow-up; all material evidence remains pending EP review." };
  return { variables, plan };
}
export async function fingerprintVariables(variables: Record<string, Scalar>) { const ordered = Object.fromEntries(Object.entries(variables).sort(([a], [b]) => a.localeCompare(b))); const hash = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(JSON.stringify(ordered))); return Array.from(new Uint8Array(hash), (byte) => byte.toString(16).padStart(2, "0")).join(""); }
