import { ArrowUpRight, FileInput, FlaskConical, MessageSquareText, PhoneCall } from "lucide-react";
import type { Metadata } from "next";
export const metadata:Metadata={title:"Try Wever Callback",description:"Follow a consignment inquiry from a customer's callback request to a conversation and an operator-confirmed next step."};
export default function Demo(){
  return <main className="demo-page">
    <header className="customer-brand"><PhoneCall size={26}/><div><p className="eyebrow">WEVER LABS</p><strong>Callback.</strong></div><a className="text-link" href="/">Your workspace <ArrowUpRight size={17}/></a></header>
    <section className="demo-intro"><p className="eyebrow">TRY THE CUSTOMER WORKFLOW</p><h1>From “I’m interested”<br/>to a clear next step.</h1><p>Wever Callback helps consignment boutiques follow up with people who ask to hear from them. Review a request, approve an AI-assisted phone interview, and act on the saved result.</p></section>
    <div className="demo-grid"><section className="customer-card"><FileInput className="demo-icon"/><span className="eyebrow">01 · THE CUSTOMER</span><h2>Request a callback</h2><p>Try the form as Maya, a fictional customer with clothing and handbags to consign. The sample stays in this page and sends nothing.</p><a className="primary-link" href="/request/demo">Try the sample form <ArrowUpRight size={17}/></a></section>
      <section className="customer-card"><FlaskConical className="demo-icon"/><span className="eyebrow">02 · THE BUSINESS</span><h2>Work through the inquiry</h2><p>Open the sample workspace on this computer. It uses fictional records and simulated conversations. No CALL-E key or credits are needed.</p><a className="primary-link" href="/?demo=1">Open sample workspace <ArrowUpRight size={17}/></a></section></div>
    <section className="demo-instructions customer-card"><MessageSquareText className="demo-icon"/><h2>Complete the walkthrough</h2><ol><li>In the sample workspace, click <strong>Load sample inquiries</strong>, then open <strong>Maya Chen</strong>.</li><li>Choose <strong>Interested, requests a consultation</strong> and run the sample rehearsal.</li><li>Open <strong>Conversation</strong> to review the dialogue and result.</li><li>Open <strong>Next steps</strong> and save a note. To practice recording a confirmed booking, select <strong>Booked by you</strong> and enter a complete date, time and time zone.</li></ol><p className="field-hint">Daniel’s pricing question and Leah’s opt-out cover cases that need a different response. Sample records are saved in your own workspace and stay separate from live customers.</p></section>
    <section className="demo-evidence"><h2>What the live product does</h2><p>Live inquiries use CALL-E after the business reviews and approves a call. The completed interview, structured result and follow-up stay with the inquiry. A requested consultation time remains unconfirmed until a team member confirms it.</p><p>An owner test completed a real phone interview on September 10, 2026. This walkthrough uses simulated conversations; it does not replay that private call. Live calls require your own CALL-E account and credits.</p></section>
    <footer className="customer-footer">Wever Callback by Wever Labs · Customer follow-up for consignment boutiques</footer>
  </main>;
}
