const string=description=>({type:'string',description});
const choice=(values,description)=>({...string(description),enum:values});
const object=properties=>({type:'object',properties,required:Object.keys(properties),additionalProperties:false});
const list=items=>({type:'array',items});
export const evidenceSchema=list(object({quote:string('Exact COMPLETE transcript turn, not a paraphrase.'),turn_index:{type:'integer',description:'Zero-based index across all bot and patient turns.'}}));
export const conversationSchema=object({
 schema_version:choice(['2'],'Structured multi-instruction care conversation.'),
 conversation:object({identity:choice(['confirmed','wrong_person','unknown'],'Explicit self identification, not an assumption.'),identity_evidence:evidenceSchema,consent:choice(['agreed','declined','unknown'],'Separate agreement to continue after identity confirmation.'),consent_evidence:evidenceSchema,ending:choice(['completed','patient_stopped','disconnected','voicemail','wrong_person','unknown'],'What actually ended this conversation.')}),
 instruction_results:list(object({order_quote:string('Exact nonempty excerpt from the original clinician instruction. Cover each distinct requirement, including unasked requirements; do not invent requirements.'),question:string('What this requirement asks us to establish.'),completion_state:choice(['completed','not_completed','partially_completed','previously_confirmed','unclear','not_asked'],'Status of the instruction, never the phone connection. Use previously_confirmed only for the exact requirement already completed in supplied verified prior findings, with empty current evidence.'),finding:string('What the patient said, including limitations. No inferred diagnosis.'),evidence:evidenceSchema})),
 patient_reports:list(object({kind:choice(['experience','barrier','understanding','concern','intention','other'],'Patient-reported information, including unprompted information outside this order.'),description:string('Factual report. Do not assign medical causality.'),reason:choice(['forgot','side_effect_concern','cannot_access_medication','does_not_understand_instruction','does_not_want_to_take','other','unknown'],'Optional classification; use unknown when not established.'),evidence:evidenceSchema})),
 patient_requests:list(object({kind:choice(['clinician_contact','explanation','practical_help','later_contact','stop_contact','other'],'What the patient requested.'),description:string('The actual request, without an invented commitment.'),evidence:evidenceSchema})),
 open_questions:list(object({question:string('Unanswered, ambiguous or contradictory issue.'),cause:choice(['not_asked','unclear','contradictory'],'Why the issue remains open.'),evidence:evidenceSchema})),
 contact_preference:object({agreement_state:choice(['none','preference','agreed'],'Agreed only for a specific contact time explicitly accepted by the patient. Medication intentions are not contact agreements.'),wording:string('Original patient preference; empty if none.'),at:string('ISO 8601 with offset only for an explicit agreement, otherwise empty. Resolve relative dates from the supplied reference and patient time zone.'),evidence:evidenceSchema,proposal_evidence:evidenceSchema}),
 review:object({required:{type:'boolean'},reason:string('Why clinician review is needed, without diagnosis or promises.'),questions:list(string('Specific question for the clinician.')),evidence:evidenceSchema}),
 care_summary:string('Concise factual summary for a clinician, including completion, concerns, requests and what remains unknown. No medical advice.')
});
