"""Incidents, and the paperwork an incident generates.

Three routers live here because they are three views of one thing: an address that needs something,
the record of what was decided about it, and the messages that go out about it.

* `/api/incidents` — what is open, where it is, what it needs, and who has been sent.
* `/api/documents` — ICS-214 activity logs, ICS-213 messages, situation reports. Generated by an
  agent from the record, and unsigned until a named human approves one. `approved_by` blank is the
  same property `HandoffPacket.released_at` null is: nobody has put their name to this.
* `/api/correspondence` — drafts to a contact, a family member, or an agency. Drafted automatically,
  `sent_at` always null. **There is no send endpoint here and there is none anywhere in this
  codebase.** A draft is words on a screen for a human to read out or to copy; the machine does not
  message a frightened relative on its own initiative.

`POST /api/incidents/sync` is the seam that turns escalations into incidents. It is a reconciler —
idempotent, safe to call repeatedly — and the same function the background loop in `app/main.py`
runs. A GET never mutates: the sync is a POST because it writes, even though everything it writes
is derived.
"""
from __future__ import annotations

from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel
from sqlmodel import Session, select

from app import obs
from app.agents import build_client, draft_agency_message, draft_contact_message, draft_family_update
from app.agents import write_activity_log, write_general_message, write_situation_report
from app.api.deps import settings_dep
from app.config import Settings
from app.db import session_scope
from app.domain import fleet
from app.domain.state import CheckOutcome, IncidentStatus
from app.models import (
    Asset,
    CheckCall,
    Correspondence,
    Dispatch,
    Escalation,
    HandoffPacket,
    Hazard,
    Incident,
    IncidentDocument,
    Neighbour,
    OperatorAction,
    Sweep,
)
from app.orchestrator import dispatch as dispatcher
from app.orchestrator import incidents as incident_layer

router = APIRouter(prefix="/api/incidents", tags=["incidents"])
documents_router = APIRouter(prefix="/api/documents", tags=["documents"])
correspondence_router = APIRouter(prefix="/api/correspondence", tags=["correspondence"])

OPEN_STATUSES = frozenset({IncidentStatus.OPEN, IncidentStatus.TRIAGED,
                           IncidentStatus.DISPATCHED, IncidentStatus.ON_SCENE})


# ------------------------------------------------------------------------------------------------
# Wire shapes
# ------------------------------------------------------------------------------------------------
class ResolveIncidentIn(BaseModel):
    """Closing an incident. A name, because "resolved" with nobody attached says somebody checked
    when nobody did."""

    resolved_by: str
    resolution: str = ""


class SyncIn(BaseModel):
    sweep_id: str | None = None
    hazard_id: str | None = None


class DocumentIn(BaseModel):
    """Generating paperwork. `form` picks the ICS form; the content comes from the record only."""

    form: str = "ICS-214"  # ICS-214 | ICS-213 | situation_report
    hazard_id: str | None = None
    incident_id: str | None = None
    to: str = ""
    to_position: str = ""
    subject: str = ""
    prepared_by: str = ""


class ApproveIn(BaseModel):
    approved_by: str


class CorrespondenceIn(BaseModel):
    """Drafting a message. `kind` picks who it is to; nothing here sends anything."""

    kind: str = "contact"  # contact | family | agency
    incident_id: str
    agency: str = "Phoenix Fire Department"
    channel: str = ""
    to_name: str = ""


# ------------------------------------------------------------------------------------------------
# Rendering
# ------------------------------------------------------------------------------------------------
def incident_out(session: Session, incident: Incident, *, full: bool = False) -> dict[str, Any]:
    nbr = session.get(Neighbour, incident.neighbour_id)
    dispatches = list(
        session.exec(select(Dispatch).where(Dispatch.incident_id == incident.id)
                     .order_by(Dispatch.proposed_at)).all()
    )
    assets = {a.id: a for a in (session.get(Asset, d.asset_id) for d in dispatches) if a is not None}
    out: dict[str, Any] = {
        "id": incident.id,
        "hazard_id": incident.hazard_id,
        "sweep_id": incident.sweep_id,
        "neighbour_id": incident.neighbour_id,
        "escalation_id": incident.escalation_id,
        "source_call_id": incident.source_call_id,
        "name": nbr.name if nbr else incident.neighbour_id,
        "status": str(incident.status),
        "priority": incident.priority,
        "priority_label": fleet.priority_label(incident.priority),
        "outcome": incident.outcome,
        "summary": incident.summary,
        "needs": list(incident.needs or []),
        "lat": incident.lat,
        "lon": incident.lon,
        "address": incident.address,
        "unit": nbr.unit if nbr else "",
        "access_notes": nbr.access_notes if nbr else "",
        "power_dependent": bool(nbr.power_dependent) if nbr else None,
        "conditions": list(nbr.conditions or []) if nbr else [],
        "mobility": nbr.mobility if nbr else "",
        "lives_alone": bool(nbr.lives_alone) if nbr else None,
        "opened_at": incident.opened_at.isoformat() + "Z",
        "resolved_at": (incident.resolved_at.isoformat() + "Z") if incident.resolved_at else None,
        "resolution": incident.resolution,
        "dispatches": [dispatcher.dispatch_out(d, assets.get(d.asset_id), incident) for d in dispatches],
        "awaiting_authorisation": [
            dispatcher.dispatch_out(d, assets.get(d.asset_id), incident)
            for d in dispatches if str(d.status) == "PROPOSED" and d.requires_authorisation
        ],
    }
    if full:
        needs = dispatcher._needs(session, incident)  # noqa: SLF001 — the same needs the dispatcher uses
        out["need_detail"] = needs.to_dict()
        out["situation"] = incident_layer.situation_for(session, incident)
        out["risk_reasons"] = incident_layer.risk_reasons_for(session, incident)
        out["documents"] = [document_out(d) for d in session.exec(
            select(IncidentDocument).where(IncidentDocument.incident_id == incident.id)).all()]
        out["correspondence"] = [correspondence_out(c) for c in session.exec(
            select(Correspondence).where(Correspondence.incident_id == incident.id)).all()]
        out["actions"] = [action_out(a) for a in session.exec(
            select(OperatorAction).where(OperatorAction.incident_id == incident.id)
            .order_by(OperatorAction.created_at)).all()]
    return out


def action_out(action: OperatorAction) -> dict[str, Any]:
    """One agent decision with enough provenance to argue with afterwards."""
    return {
        "id": action.id, "kind": action.kind, "agent": action.agent, "model": action.model,
        "rationale": action.rationale, "accepted": action.accepted, "accepted_by": action.accepted_by,
        "latency_ms": action.latency_ms, "error": action.error,
        "inputs": dict(action.inputs or {}), "output": dict(action.output or {}),
        "created_at": action.created_at.isoformat() + "Z",
    }


def document_out(doc: IncidentDocument) -> dict[str, Any]:
    return {
        "id": doc.id, "hazard_id": doc.hazard_id, "incident_id": doc.incident_id, "form": doc.form,
        "title": doc.title, "body": doc.body, "fields": dict(doc.fields or {}),
        "generated_by": doc.generated_by, "approved_by": doc.approved_by,
        "approved": bool(str(doc.approved_by or "").strip()),
        "created_at": doc.created_at.isoformat() + "Z",
    }


def correspondence_out(msg: Correspondence) -> dict[str, Any]:
    return {
        "id": msg.id, "hazard_id": msg.hazard_id, "incident_id": msg.incident_id,
        "neighbour_id": msg.neighbour_id, "channel": msg.channel, "to_name": msg.to_name,
        "to_ref": msg.to_ref, "subject": msg.subject, "body": msg.body,
        "drafted_by": msg.drafted_by, "approved_by": msg.approved_by,
        "approved": bool(str(msg.approved_by or "").strip()),
        "sent_at": (msg.sent_at.isoformat() + "Z") if msg.sent_at else None,
        # Stated, not inferred. Nothing in BuddyE can set sent_at.
        "status_note": "draft — approved, ready for a human to send" if msg.approved_by
        else "draft — nobody has been contacted",
        "created_at": msg.created_at.isoformat() + "Z",
    }


# ------------------------------------------------------------------------------------------------
# Incidents
# ------------------------------------------------------------------------------------------------
@router.get("")
def list_incidents(
    hazard_id: str | None = Query(default=None),
    sweep_id: str | None = Query(default=None),
    open_only: bool = Query(default=False),
) -> list[dict[str, Any]]:
    with session_scope() as s:
        q = select(Incident)
        if hazard_id:
            q = q.where(Incident.hazard_id == hazard_id)
        if sweep_id:
            q = q.where(Incident.sweep_id == sweep_id)
        rows = list(s.exec(q).all())
        if open_only:
            rows = [i for i in rows if IncidentStatus(i.status) in OPEN_STATUSES]
        # Worst first: priority 1 is life safety, and a board sorted by time of arrival buries it.
        rows.sort(key=lambda i: (int(i.priority or 5), i.opened_at))
        return [obs.redact(incident_out(s, i)) for i in rows]


@router.post("/sync")
def sync(body: SyncIn | None = None) -> dict[str, Any]:
    """Make the incident table agree with the escalations. Idempotent; safe to call at any time."""
    body = body or SyncIn()
    with session_scope() as s:
        if body.sweep_id:
            opened = incident_layer.sync_sweep(s, body.sweep_id)
        elif body.hazard_id:
            opened = incident_layer.sync_hazard(s, body.hazard_id)
        else:
            sweeps = list(s.exec(select(Sweep)).all())
            opened = [i for sweep in sweeps for i in incident_layer.sync_sweep(s, sweep.id)]
        s.flush()
        payloads = [incident_layer.event_payload(i) for i in opened]
        total = len(list(s.exec(select(Incident)).all()))
    incident_layer.announce(payloads)
    return {"opened": [p["incident_id"] for p in payloads], "incidents": total}


@router.get("/{incident_id}")
def get_incident(incident_id: str) -> dict[str, Any]:
    with session_scope() as s:
        incident = s.get(Incident, incident_id)
        if incident is None:
            raise HTTPException(404, "incident not found")
        return obs.redact(incident_out(s, incident, full=True))


@router.get("/{incident_id}/candidates")
def candidates(incident_id: str) -> dict[str, Any]:
    """Who could go, and a sentence naming every unit that could not.

    The exclusions are the point. A coordinator who asks "why didn't you send WV-2?" and gets
    silence stops using the tool, so the answer is on the screen before they ask.
    """
    with session_scope() as s:
        incident = s.get(Incident, incident_id)
        if incident is None:
            raise HTTPException(404, "incident not found")
        return obs.redact(dispatcher.eligibility_for(s, incident).to_dict())


@router.post("/{incident_id}/resolve")
def resolve_incident(incident_id: str, body: ResolveIncidentIn) -> dict[str, Any]:
    with session_scope() as s:
        incident = s.get(Incident, incident_id)
        if incident is None:
            raise HTTPException(404, "incident not found")
        try:
            incident_layer.resolve(s, incident, resolved_by=body.resolved_by, resolution=body.resolution)
        except incident_layer.IncidentRefused as exc:
            raise HTTPException(400, str(exc)) from exc
        s.flush()
        return obs.redact(incident_out(s, incident))


# ------------------------------------------------------------------------------------------------
# Documents
# ------------------------------------------------------------------------------------------------
def _hazard_record(session: Session, hazard: Hazard | None) -> dict[str, Any]:
    if hazard is None:
        return {}
    return {"kind": hazard.kind, "headline": hazard.headline, "area": hazard.area,
            "severity": hazard.severity, "starts_at": hazard.starts_at, "ends_at": hazard.ends_at}


def _entries_for_incident(session: Session, incident: Incident) -> list[dict[str, Any]]:
    """The incident's own timeline, from rows only. Nothing here is narrated.

    A quote is carried on the entry that has one, verbatim from a `CheckCall`; the documentation
    agent's grounding check refuses any quote in a generated body that is not in this record.
    """
    entries: list[dict[str, Any]] = []
    calls = list(session.exec(select(CheckCall).where(
        CheckCall.neighbour_id == incident.neighbour_id,
        CheckCall.sweep_id == incident.sweep_id,
    )).all())
    for call in sorted(calls, key=lambda c: c.started_at or c.completed_at or incident.opened_at):
        concerns = list(call.concerns or [])
        entries.append({
            "at": call.completed_at or call.started_at,
            "text": f"Check-in call to {call.callee} ended {call.status}"
                    + (f"; outcome {call.outcome}" if call.outcome else ""),
            "quote": concerns[0] if concerns else "",
        })
    esc = session.get(Escalation, incident.escalation_id) if incident.escalation_id else None
    if esc is not None:
        for rung in (esc.rungs or []):
            entries.append({"at": rung.get("at"), "text": f"{rung.get('level')}: {rung.get('action')}"
                                                          f" — {rung.get('result') or rung.get('note') or ''}"})
    entries.append({"at": incident.opened_at,
                    "text": f"Incident opened, priority {incident.priority} "
                            f"({fleet.priority_label(incident.priority)}); needs "
                            f"{', '.join(incident.needs or []) or 'not recorded'}"})
    for d in session.exec(select(Dispatch).where(Dispatch.incident_id == incident.id)).all():
        entries.append({
            "at": d.committed_at or d.proposed_at,
            "text": f"Dispatch {d.status}: {d.reason or 'no reason recorded'}"
                    + (f" (authorised by {d.authorised_by})" if d.authorised_by else "")
                    + (f" ({d.decline_reason})" if d.decline_reason else ""),
        })
    return entries


def _stats_for_hazard(session: Session, hazard_id: str) -> dict[str, Any]:
    """Counts, from rows. The documentation agent may describe these; it may not recount them."""
    sweeps = list(session.exec(select(Sweep).where(Sweep.hazard_id == hazard_id)).all())
    outcomes: dict[str, int] = {}
    for sweep in sweeps:
        for value in (sweep.outcomes or {}).values():
            outcomes[str(value)] = outcomes.get(str(value), 0) + 1
    incidents = list(session.exec(select(Incident).where(Incident.hazard_id == hazard_id)).all())
    dispatches = [d for i in incidents for d in session.exec(
        select(Dispatch).where(Dispatch.incident_id == i.id)).all()]
    packets = list(session.exec(select(HandoffPacket).where(HandoffPacket.hazard_id == hazard_id)).all())
    return {
        "calls_made": sum(s.calls_made for s in sweeps),
        "contacted": sum(v for k, v in outcomes.items() if k != CheckOutcome.UNREACHABLE.value),
        "unreachable": outcomes.get(CheckOutcome.UNREACHABLE.value, 0),
        "urgent": outcomes.get(CheckOutcome.URGENT.value, 0),
        "needs_help": outcomes.get(CheckOutcome.NEEDS_HELP.value, 0),
        "safe": outcomes.get(CheckOutcome.SAFE.value, 0),
        "incidents_open": sum(1 for i in incidents if IncidentStatus(i.status) in OPEN_STATUSES),
        "incidents_total": len(incidents),
        "dispatches_committed": sum(1 for d in dispatches if str(d.status) not in {"PROPOSED", "CANCELLED"}),
        "dispatches_awaiting_authorisation": sum(
            1 for d in dispatches if str(d.status) == "PROPOSED" and d.requires_authorisation),
        "handoffs_prepared": len(packets),
        "handoffs_released": sum(1 for p in packets if p.released_at is not None),
    }


@documents_router.get("")
def list_documents(hazard_id: str | None = Query(default=None),
                   incident_id: str | None = Query(default=None)) -> list[dict[str, Any]]:
    with session_scope() as s:
        q = select(IncidentDocument)
        if hazard_id:
            q = q.where(IncidentDocument.hazard_id == hazard_id)
        if incident_id:
            q = q.where(IncidentDocument.incident_id == incident_id)
        rows = list(s.exec(q.order_by(IncidentDocument.created_at)).all())
        return [obs.redact(document_out(d)) for d in rows]


@documents_router.post("/generate")
async def generate_document(body: DocumentIn, settings: Settings = Depends(settings_dep)) -> dict[str, Any]:
    """Write one ICS form from the record. Unsigned: `approved_by` stays blank until a human signs."""
    return await generate_document_record(body, settings)


async def generate_document_record(body: DocumentIn, settings: Settings) -> dict[str, Any]:
    """The work behind `POST /api/documents/generate`, shared with the after-call pipeline.

    The session is closed before the agent is awaited — see `app/orchestrator/dispatch.py` for why
    a model call must never sit inside an open sqlite transaction.
    """
    with session_scope() as s:
        incident = s.get(Incident, body.incident_id) if body.incident_id else None
        hazard_id = body.hazard_id or (incident.hazard_id if incident else "")
        hazard = s.get(Hazard, hazard_id) if hazard_id else None
        if hazard is None and incident is None:
            raise HTTPException(404, "generate a document for a hazard or an incident that exists")
        hazard_record = _hazard_record(s, hazard)
        entries = _entries_for_incident(s, incident) if incident is not None else []
        incident_record = incident_out(s, incident) if incident is not None else None
        stats = _stats_for_hazard(s, hazard_id) if hazard_id else {}
        hazard_id = hazard_id or (hazard.id if hazard else "")

    client = build_client(settings)
    prepared_by = body.prepared_by or settings.OVERSEER_NAME or settings.BLOCK_CAPTAIN_NAME
    form = body.form.strip()
    if form == "ICS-213":
        doc = await write_general_message(
            hazard_id=hazard_id, hazard=hazard_record, to=body.to or "Phoenix Fire Department",
            to_position=body.to_position, frm=prepared_by,
            subject=body.subject or (f"Welfare incident — {incident_record['address']}" if incident_record else "Welfare sweep"),
            message_record={"incident": incident_record or {}, "stats": stats},
            incident_id=body.incident_id, client=client,
        )
    elif form == "situation_report":
        doc = await write_situation_report(
            hazard_id=hazard_id, hazard=hazard_record, stats=stats,
            entries=entries, prepared_by=prepared_by, client=client,
        )
    else:
        doc = await write_activity_log(
            hazard_id=hazard_id, hazard=hazard_record, entries=entries,
            incident_id=body.incident_id, incident=incident_record,
            prepared_by=prepared_by, client=client,
        )

    with session_scope() as s:
        row = IncidentDocument(**doc)
        s.add(row)
        s.flush()
        out = obs.redact(document_out(row))
    # On the stream so an open incident card shows the new form without being reloaded.
    from app.events.bus import bus
    bus.publish(hazard_id=hazard_id, type="document.generated",
                payload={"document_id": out.get("id"), "form": out.get("form"), "incident_id": body.incident_id})
    return out


@documents_router.get("/{document_id}")
def get_document(document_id: str) -> dict[str, Any]:
    with session_scope() as s:
        doc = s.get(IncidentDocument, document_id)
        if doc is None:
            raise HTTPException(404, "document not found")
        return obs.redact(document_out(doc))


@documents_router.post("/{document_id}/approve")
def approve_document(document_id: str, body: ApproveIn) -> dict[str, Any]:
    """A human signs the form. The same name rule as everywhere else: a service account is not a
    person, and an ICS form signed by "system" is a form nobody signed."""
    from app.orchestrator import escalate as ladder

    with session_scope() as s:
        doc = s.get(IncidentDocument, document_id)
        if doc is None:
            raise HTTPException(404, "document not found")
        try:
            doc.approved_by = ladder._validate_releaser(body.approved_by)  # noqa: SLF001
        except ladder.ReleaseRefused as exc:
            raise HTTPException(400, str(exc)) from exc
        s.add(doc)
        s.flush()
        return obs.redact(document_out(doc))


# ------------------------------------------------------------------------------------------------
# Correspondence
# ------------------------------------------------------------------------------------------------
@correspondence_router.get("")
def list_correspondence(hazard_id: str | None = Query(default=None),
                        incident_id: str | None = Query(default=None)) -> list[dict[str, Any]]:
    with session_scope() as s:
        q = select(Correspondence)
        if hazard_id:
            q = q.where(Correspondence.hazard_id == hazard_id)
        if incident_id:
            q = q.where(Correspondence.incident_id == incident_id)
        rows = list(s.exec(q.order_by(Correspondence.created_at)).all())
        return [obs.redact(correspondence_out(m)) for m in rows]


@correspondence_router.post("/draft")
async def draft(body: CorrespondenceIn, settings: Settings = Depends(settings_dep)) -> dict[str, Any]:
    """Draft a message about one incident. Nothing is sent, here or anywhere."""
    with session_scope() as s:
        incident = s.get(Incident, body.incident_id)
        if incident is None:
            raise HTTPException(404, "incident not found")
        nbr = s.get(Neighbour, incident.neighbour_id)
        hazard = s.get(Hazard, incident.hazard_id)
        hazard_record = _hazard_record(s, hazard)
        neighbour_record = {
            "id": incident.neighbour_id,
            "name": nbr.name if nbr else incident.neighbour_id,
            "address": incident.address, "unit": nbr.unit if nbr else "",
            "access_notes": nbr.access_notes if nbr else "",
            "age_band": nbr.age_band if nbr else "", "lives_alone": bool(nbr.lives_alone) if nbr else None,
            "mobility": nbr.mobility if nbr else "", "conditions": list(nbr.conditions or []) if nbr else [],
            "power_dependent": bool(nbr.power_dependent) if nbr else None,
            "contact_name": nbr.contact_name if nbr else "", "contact_phone": nbr.contact_phone if nbr else "",
            "contact_relation": nbr.contact_relation if nbr else "",
        }
        calls = list(s.exec(select(CheckCall).where(
            CheckCall.neighbour_id == incident.neighbour_id, CheckCall.sweep_id == incident.sweep_id,
            CheckCall.callee == "neighbour").order_by(CheckCall.attempt)).all())
        attempts = [{"at": c.started_at, "outcome": c.outcome or c.status, "status": c.status} for c in calls]
        packet_row = None
        if incident.escalation_id:
            packet_row = s.exec(select(HandoffPacket).where(
                HandoffPacket.escalation_id == incident.escalation_id)).first()
        packet = {
            "last_contact_at": packet_row.last_contact_at if packet_row else None,
            "last_words": packet_row.last_words if packet_row else "",
            "concerns": list(packet_row.concerns or []) if packet_row else [],
            "attempts_summary": list(packet_row.attempts_summary or []) if packet_row else attempts,
            "recommended_action": packet_row.recommended_action if packet_row else incident.summary,
        }
        visit = _visit_record(s, incident)
        hazard_id = incident.hazard_id

    client = build_client(settings)
    captain = settings.BLOCK_CAPTAIN_NAME
    kind = body.kind.strip().lower()
    if kind == "family":
        msg = await draft_family_update(
            hazard_id=hazard_id, hazard=hazard_record, neighbour=neighbour_record, visit=visit,
            incident_id=body.incident_id, channel=body.channel or "sms", captain_name=captain,
            to_name=body.to_name, client=client,
        )
    elif kind == "agency":
        msg = await draft_agency_message(
            hazard_id=hazard_id, hazard=hazard_record, neighbour=neighbour_record, packet=packet,
            agency=body.agency, incident_id=body.incident_id,
            channel=body.channel or "call_script", captain_name=captain, client=client,
        )
    else:
        msg = await draft_contact_message(
            hazard_id=hazard_id, hazard=hazard_record, neighbour=neighbour_record, attempts=attempts,
            incident_id=body.incident_id, channel=body.channel or "sms", captain_name=captain,
            client=client,
        )

    with session_scope() as s:
        row = Correspondence(**msg)
        s.add(row)
        s.flush()
        out = obs.redact(correspondence_out(row))
    from app.events.bus import bus
    bus.publish(hazard_id=hazard_id, type="correspondence.drafted",
                payload={"message_id": out.get("id"), "kind": kind, "incident_id": body.incident_id})
    return out


@correspondence_router.get("/{message_id}")
def get_correspondence(message_id: str) -> dict[str, Any]:
    with session_scope() as s:
        msg = s.get(Correspondence, message_id)
        if msg is None:
            raise HTTPException(404, "message not found")
        return obs.redact(correspondence_out(msg))


@correspondence_router.post("/{message_id}/approve")
def approve_correspondence(message_id: str, body: ApproveIn) -> dict[str, Any]:
    """A human approves a draft for a human to send.

    Approving is not sending, and `sent_at` stays null: there is no send path in this codebase. What
    approval means is that a named person read the words and is willing to have them go out under
    their name, which is exactly the boundary `HandoffPacket.released_at` draws.
    """
    from app.orchestrator import escalate as ladder

    with session_scope() as s:
        msg = s.get(Correspondence, message_id)
        if msg is None:
            raise HTTPException(404, "message not found")
        try:
            msg.approved_by = ladder._validate_releaser(body.approved_by)  # noqa: SLF001
        except ladder.ReleaseRefused as exc:
            raise HTTPException(400, str(exc)) from exc
        s.add(msg)
        s.flush()
        return obs.redact(correspondence_out(msg))


def _visit_record(session: Session, incident: Incident) -> dict[str, Any]:
    """What actually happened at the address, from the dispatch rows. Never a narrative.

    An unarrived dispatch says so; that is the honest answer and it is what stops a family update
    saying somebody has been round when nobody has.
    """
    rows = list(session.exec(select(Dispatch).where(Dispatch.incident_id == incident.id)
                             .order_by(Dispatch.proposed_at)).all())
    arrived = [d for d in rows if d.arrived_at is not None]
    if not arrived:
        return {"who": "", "arrived_at": None,
                "found": "nobody has been to the address yet",
                "actions": "nothing has been delivered or done at the address",
                "outstanding": ", ".join(incident.needs or []) or "not recorded"}
    latest = arrived[-1]
    asset = session.get(Asset, latest.asset_id)
    return {
        "who": f"{asset.call_sign} ({asset.operator_name})" if asset else latest.asset_id,
        "arrived_at": latest.arrived_at,
        "found": incident.summary or "not recorded",
        "actions": f"{asset.call_sign} attended and covered {', '.join(incident.needs or []) or 'the request'}"
                   if asset else "attended",
        "outstanding": incident.resolution or "the incident is still open",
    }
