// Auto-generated by sync.mjs — the pure verification core.
export { decide } from "./gate/decide.js";
export * from "./gate/evidence.js";
export { REASON_CODES, type ReasonCode } from "./gate/reasons.js";
export { parseTranscript, type ParseContext } from "./parser/parseTranscript.js";
export * as dateGrammar from "./parser/dateGrammar.js";
export { detect, type DetectInput } from "./ambiguity/detect.js";
export {
  normalizePattern,
  skeleton,
  assertPatternPiiClean,
  PatternValidationError,
} from "./fixtures/normalizePattern.js";
export * from "./domain/types.js";
export * from "./domain/booking.js";
