import test from 'node:test';import assert from 'node:assert/strict';
import {freshBreastWorkspace} from './src/breast/demo.mjs';
import {classifyBreastRisk,validateModelRisk} from './src/breast/model-risk.mjs';
import {generateClinicianScript,scriptContext} from './src/breast/model-script.mjs';
import {applyOutcome} from './src/care-result.mjs';
import {breastCallGoal} from './src/breast/prompt.mjs';
const env={AVELIS_PLANNER_KEY:'fake',AVELIS_PLANNER_MODEL:'test',AVELIS_PLANNER_ORIGIN:'https://api.deepseek.com'},db=freshBreastWorkspace();
function fixture(){const patient=db.patients[0],task=db.tasks.find(t=>t.patient_id===patient.id),call=db.calls.find(c=>c.id===task.call_id);return {db,patient,task,call};}
const reply=x=>({ok:true,json:async()=>({choices:[{message:{content:JSON.stringify(x)}}]})});
test('model chooses risk and routing; exact evidence is validated without running symptom rules',async()=>{const {task,call}=fixture();const evidence=call.conversation_report.oncology.symptoms[0].facts[0].evidence;let input;const result=await classifyBreastRisk({task,report:call.conversation_report,transcript:call.transcript,verification:call.semantic_verification},env,{fetcher:async(_url,o)=>{input=JSON.parse(JSON.parse(o.body).messages[1].content);return reply({level:'YELLOW',routing:'HUMAN_REVIEW',reason:'Sleep impact requires assessment',triggers:[{label:'Sleep affected',evidence:evidence.slice(0,1)}],missing:[]});}});assert.equal(result.source,'DeepSeek');assert.equal(input.original_instruction,task.order.instruction);assert.ok(input.transcript.length>30);assert.equal(result.routing,'HUMAN_REVIEW');});
test('invalid quotes and unsupported GREEN are rejected',()=>{const {task,call}=fixture(),context={task,report:call.conversation_report,transcript:call.transcript,verification:{supported:false}};assert.throws(()=>validateModelRisk({level:'GREEN',routing:'COMPLETED',reason:'Fine',triggers:[],missing:[]},context));assert.throws(()=>validateModelRisk({level:'RED',routing:'HUMAN_REVIEW',reason:'Concern',triggers:[{label:'Invented',evidence:[{turn_index:1,quote:'not here'}]}],missing:[]},context));});
test('live breast result without model classification remains UNKNOWN even with a verified report',()=>{const d=structuredClone(db),t=d.tasks[0],c=d.calls.find(c=>c.task_id===t.id);c.provider='calle';applyOutcome(d,c,{status:'COMPLETED',result:{transcript:c.transcript,extracted:{conversation_result:c.conversation_report}}},c.semantic_verification);assert.equal(c.risk_assessment.level,'UNKNOWN');assert.equal(t.status,'UNRESOLVED');});
test('script model receives original order, full transcript and clinician actions',async()=>{const f=fixture(),context=scriptContext({...f,clinician:{name:'Dr Sarah Chen'}});let input;const evidence=f.call.conversation_report.oncology.symptoms[0].facts[0].evidence.slice(0,1);const result=await generateClinicianScript(context,env,{fetcher:async(_url,o)=>{if(JSON.parse(o.body).messages[0].content.startsWith('Review '))return reply({accepted:true,issues:[]});input=JSON.parse(JSON.parse(o.body).messages[1].content);return reply({title:'Emma follow-up',script:'Hello Emma, this is Dr Sarah Chen. Is now a private time to talk? How have the hot flashes and sleep been since the last call? What has changed with your arm?',evidence,unresolved:['Current symptoms']});}});assert.ok(input.original_instruction);assert.ok(input.transcript.length>30);assert.equal(input.clinician.name,'Dr Sarah Chen');assert.equal(result.source,'DeepSeek');});
test('Live role prompt no longer introduces a fictional service',()=>{const p=breastCallGoal(fixture().task);assert.doesNotMatch(p,/synthetic demonstration|in this DRAFT demo|external interrupt is NOT connected in this demo/);assert.match(p,/Identify yourself as Avelis/);});
test('a rejected clinician draft is rewritten once with reviewer feedback; repeated rejection fails',async()=>{
 const context=scriptContext({...fixture(),clinician:{name:'Dr Chen'}});let drafts=0,reviews=0,feedback;
 const draft={title:'Emma follow-up',script:'Hello Emma, this is Dr Chen. Is now a private time to talk? How have the hot flashes and sleep been since the last call? What has changed with your arm?',evidence:fixture().call.conversation_report.oncology.symptoms[0].facts[0].evidence.slice(0,1),unresolved:[]};
 const fetcher=async(_url,o)=>{const body=JSON.parse(o.body);if(body.messages[0].content.startsWith('Review ')){reviews++;return reply({accepted:reviews>1,issues:reviews===1?[{kind:'unsupported_assertion',excerpt:draft.script.slice(0,20),source_gap:'',reason:'Remove an unsupported statement.'}]:[]});}drafts++;feedback=JSON.parse(body.messages[1].content).revision_feedback;return reply(draft);};
 const result=await generateClinicianScript(context,env,{fetcher});assert.equal(result.reviewed,true);assert.equal(drafts,2);assert.deepEqual(feedback,[{kind:'unsupported_assertion',excerpt:draft.script.slice(0,20),source_gap:'',reason:'Remove an unsupported statement.'}]);
 let rejected=0;await assert.rejects(generateClinicianScript(context,env,{fetcher:async(_url,o)=>{if(JSON.parse(o.body).messages[0].content.startsWith('Review ')){rejected++;return reply({accepted:false,issues:[{kind:'unsupported_assertion',excerpt:draft.script.slice(0,20),source_gap:'',reason:'Unsupported claim.'}]});}return reply(draft);}}),/did not pass/);assert.equal(rejected,2);
});
