"""add disease protocols

Revision ID: 994284f27cc3
Revises: 20260729_0001
Create Date: 2026-08-03 15:38:06.463441+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '994284f27cc3'
down_revision: Union[str, None] = '20260729_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease_protocols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('needs_followup_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disease_protocols_code'), 'disease_protocols', ['code'], unique=True)
    op.create_table('protocol_emergency_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['disease_protocols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocol_emergency_keywords_protocol_id'), 'protocol_emergency_keywords', ['protocol_id'], unique=False)
    op.create_table('protocol_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['disease_protocols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocol_questions_protocol_id'), 'protocol_questions', ['protocol_id'], unique=False)
    op.create_table('protocol_result_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=128), nullable=False),
    sa.Column('field_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('minimum', sa.Integer(), nullable=True),
    sa.Column('maximum', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['disease_protocols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocol_id', 'field_key')
    )
    op.create_index(op.f('ix_protocol_result_fields_protocol_id'), 'protocol_result_fields', ['protocol_id'], unique=False)
    op.create_table('protocol_result_field_enums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['protocol_result_fields.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_id', 'value')
    )
    op.create_index(op.f('ix_protocol_result_field_enums_field_id'), 'protocol_result_field_enums', ['field_id'], unique=False)
    op.add_column('patients', sa.Column('needs_followup', sa.Boolean(), nullable=True))
    op.add_column('patients', sa.Column('protocol_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patients', 'disease_protocols', ['protocol_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'protocol_id')
    op.drop_column('patients', 'needs_followup')
    op.drop_index(op.f('ix_protocol_result_field_enums_field_id'), table_name='protocol_result_field_enums')
    op.drop_table('protocol_result_field_enums')
    op.drop_index(op.f('ix_protocol_result_fields_protocol_id'), table_name='protocol_result_fields')
    op.drop_table('protocol_result_fields')
    op.drop_index(op.f('ix_protocol_questions_protocol_id'), table_name='protocol_questions')
    op.drop_table('protocol_questions')
    op.drop_index(op.f('ix_protocol_emergency_keywords_protocol_id'), table_name='protocol_emergency_keywords')
    op.drop_table('protocol_emergency_keywords')
    op.drop_index(op.f('ix_disease_protocols_code'), table_name='disease_protocols')
    op.drop_table('disease_protocols')
    # ### end Alembic commands ###
